//	https://img6.99.com/yhkd/image/data/hero/head/
// .jpg

var tag = [
   "1" = "fuerza",
   "2" = "agilidad",
   "3" = "inteligencia"
]

var HeroesData = [
    {
        id: 3001,
        name: "Yang Jian",
        type: "2",
        hid: 119,
        newType: "assassin",
    },
    {
        id: 240001,
        name: "Murry",
        type: "1",
        hid: 118,
        newType: "Warrior",
    },
    {
        id: 128001,
        name: "ç«å…ƒç´ ",
        type: "2",
        hid: 155,
        newType: "å°„æ‰‹/æˆ˜å£«",
    },
    {
        id: 24001,
        name: "æ£®æž—ä¹‹å¥³",
        type: "3",
        hid: 154,
        newType: "è¾…åŠ©",
    },
    {
        id: 75001,
        name: "æ··æ²Œä¹‹æº",
        type: "1",
        hid: 153,
        newType: "æˆ˜å£«",
    },
    { id: 48001, name: "é›ªè±¹", type: "2", hid: 151, newType: "æˆ˜å£«" },
    {
        id: 182001,
        name: "è¶…æ¢°å°‘å¥³",
        type: "1",
        hid: 152,
        newType: "æˆ˜å£«",
    },
    {
        id: 164001,
        name: "æ½®æ±å®ˆæœ›è€…",
        type: "2",
        hid: 150,
        newType: "åˆºå®¢",
    },
    {
        id: 66001,
        name: "å‡¯æ’’å¤§å¸",
        type: "1",
        hid: 149,
        newType: "æˆ˜å£«",
    },
    {
        id: 902001,
        name: "é›…å„¿è´å¾·",
        type: "1",
        hid: 142,
        newType: "æˆ˜å£«",
    },
    {
        id: 903001,
        name: "çµæ¢¦ç‹¼çŽ‹",
        type: "1",
        hid: 143,
        newType: "æˆ˜å£«",
    },
    { id: 904001, name: "èŒƒæµ·è¾›", type: "2", hid: 144, newType: "å°„æ‰‹" },
    {
        id: 905001,
        name: "å¨œè´æ‹‰å°”",
        type: "2",
        hid: 145,
        newType: "åˆºå®¢",
    },
    { id: 906001, name: "è‰¾å¤šçŽ›", type: "1", hid: 146, newType: "æˆ˜å£«" },
    {
        id: 907001,
        name: "æš–å¿ƒå¥³ä»†",
        type: "1",
        hid: 148,
        newType: "æˆ˜å£«",
    },
    { id: 908001, name: "å¤æé›…", type: "1", hid: 147, newType: "æˆ˜å£«" },
    { id: 909001, name: "è‹å½±", type: "2", hid: 140, newType: "åˆºå®¢" },
    { id: 155001, name: "é‡‘å…ƒç´ ", type: "2", hid: 139, newType: "æˆ˜å£«" },
    { id: 44001, name: "ä¹å°¾å¤©ç‹", type: "3", hid: 138, newType: "æ³•å¸ˆ" },
    { id: 158001, name: "ç²¾å«", type: "3", hid: 137, newType: "å°„æ‰‹" },
    {
        id: 181001,
        name: "é‡‘èŸ¾ç«¥å­",
        type: "1",
        hid: 136,
        newType: "æˆ˜å£«",
    },
    {
        id: 180001,
        name: "é£Žæš´ä¹‹çµ",
        type: "3",
        hid: 135,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 175001,
        name: "é¹¤é“å¤§å¸ˆ",
        type: "2",
        hid: 134,
        newType: "åˆºå®¢",
    },
    {
        id: 179001,
        name: "ä¸œæ–¹æœˆåˆ",
        type: "3",
        hid: 133,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 178001,
        name: "æ¶‚å±±çº¢çº¢",
        type: "1",
        hid: 132,
        newType: "æˆ˜å£«",
    },
    { id: 177001, name: "ç™½æœˆåˆ", type: "2", hid: 131, newType: "åˆºå®¢" },
    {
        id: 176001,
        name: "æ¶‚å±±è‹è‹",
        type: "3",
        hid: 130,
        newType: "è¾…åŠ©",
    },
    {
        id: 163001,
        name: "é“æ‰‡å…¬ä¸»",
        type: "2",
        hid: 129,
        newType: "å°„æ‰‹",
    },
    {
        id: 161001,
        name: "æ™®ç½—ç±³ä¿®æ–¯",
        type: "1",
        hid: 128,
        newType: "å°„æ‰‹",
    },
    {
        id: 139001,
        name: "è‡ªç„¶ä¹‹çµ",
        type: "3",
        hid: 127,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 144001,
        name: "ä¸‰è—ç¦…å¸ˆ",
        type: "3",
        hid: 126,
        newType: "æ³•å¸ˆ",
    },
    { id: 174001, name: "ç±³èŽ‰å§†", type: "1", hid: 125, newType: "æˆ˜å£«" },
    { id: 145001, name: "å¤§ä¹”", type: "3", hid: 124, newType: "æ³•å¸ˆ" },
    { id: 124001, name: "ç‹¼è››", type: "2", hid: 123, newType: "åˆºå®¢" },
    {
        id: 135001,
        name: "ç¥žç§˜å†’é™©å®¶",
        type: "3",
        hid: 122,
        newType: "æ³•å¸ˆ",
    },
    { id: 143001, name: "åˆ©å§†é²", type: "2", hid: 121, newType: "åˆºå®¢" },
    { id: 142001, name: "å¬´æ”¿", type: "3", hid: 120, newType: "æ³•å¸ˆ" },
    { id: 3001, name: "æ¨æˆ¬", type: "2", hid: 119, newType: "æˆ˜å£«" },
    {
        id: 240001,
        name: "å†¥çŽ‹å“ˆè¿ªæ–¯",
        type: "2",
        hid: 118,
        newType: "æˆ˜å£«",
    },
    {
        id: 153001,
        name: "å¹»æ°´ä»™çµ",
        type: "1",
        hid: 116,
        newType: "æˆ˜å£«",
    },
    {
        id: 90001,
        name: "æ³°å¦å·¨äºº",
        type: "1",
        hid: 108,
        newType: "æˆ˜å£«",
    },
    {
        id: 160001,
        name: "æˆ˜æ–—å¥³ç¥ž",
        type: "1",
        hid: 115,
        newType: "æˆ˜å£«",
    },
    {
        id: 172001,
        name: "è¶…æ ¸ç¥žå…µ",
        type: "3",
        hid: 113,
        newType: "æ³•å¸ˆ",
    },
    { id: 154001, name: "ç‹„ä»æ°", type: "2", hid: 112, newType: "å°„æ‰‹" },
    { id: 78001, name: "æ´›ç¥ž", type: "3", hid: 109, newType: "æ³•å¸ˆ" },
    {
        id: 171001,
        name: "ç‘žé¼ å°ä»™",
        type: "2",
        hid: 110,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 10001,
        name: "ç»‡ç”°ä¿¡é•¿",
        type: "2",
        hid: 107,
        newType: "æˆ˜å£«",
    },
    {
        id: 125001,
        name: "è‹å¤©ä¹‹æ‹³",
        type: "1",
        hid: 105,
        newType: "æˆ˜å£«",
    },
    {
        id: 168001,
        name: "åŒ—è½å¸ˆé—¨",
        type: "1",
        hid: 106,
        newType: "æˆ˜å£«",
    },
    { id: 152001, name: "å¤ä¾¯æƒ‡", type: "1", hid: 104, newType: "æˆ˜å£«" },
    {
        id: 31001,
        name: "æ—¶ç©ºçŒŽæ‰‹",
        type: "3",
        hid: 103,
        newType: "æ³•å¸ˆ",
    },
    { id: 169001, name: "èŽ«èŽ«", type: "1", hid: 111, newType: "æˆ˜å£«" },
    {
        id: 173001,
        name: "æ½˜å¤šæ‹‰â€¢äºšå…‹ç‰¹",
        type: "3",
        hid: 114,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 29001,
        name: "çŸ³ç”²å®ˆæŠ¤è€…",
        type: "1",
        hid: 98,
        newType: "å¦å…‹",
    },
    {
        id: 132001,
        name: "ç«èˆžæ­Œçµ",
        type: "3",
        hid: 101,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 105001,
        name: "æš—é»‘å†¥ç¥ž",
        type: "2",
        hid: 96,
        newType: "åˆºå®¢",
    },
    { id: 167001, name: "å¤é“ƒ", type: "3", hid: 102, newType: "æ³•å¸ˆ" },
    { id: 166001, name: "æ›¹ç„±å…µ", type: "3", hid: 100, newType: "æ³•å¸ˆ" },
    {
        id: 165001,
        name: "å°‘å¹´æ›¹ç„±å…µ",
        type: "2",
        hid: 99,
        newType: "åˆºå®¢",
    },
    { id: 162001, name: "é˜¿ä¿®ç½—", type: "2", hid: 97, newType: "åˆºå®¢" },
    { id: 58001, name: "ä¸›æž—ä¹‹å­", type: "2", hid: 95, newType: "å°„æ‰‹" },
    { id: 148001, name: "æŽç™½", type: "2", hid: 94, newType: "åˆºå®¢" },
    { id: 21001, name: "ç–¯ç‹‚åšå£«", type: "1", hid: 93, newType: "å°„æ‰‹" },
    {
        id: 54001,
        name: "ç»¿é‡ŽèŠ±ä»™",
        type: "3",
        hid: 92,
        newType: "æ³•å¸ˆ",
    },
    { id: 141001, name: "ç¥žé›•ä¾ ", type: "1", hid: 91, newType: "æˆ˜å£«" },
    { id: 137001, name: "æ›¹æ“", type: "3", hid: 90, newType: "æ³•å¸ˆ" },
    {
        id: 133001,
        name: "å®«æœ¬æ­¦è—",
        type: "2",
        hid: 89,
        newType: "åˆºå®¢",
    },
    {
        id: 87001,
        name: "å‡‹é›¶éª‘å£«",
        type: "1",
        hid: 88,
        newType: "æˆ˜å£«",
    },
    { id: 92001, name: "æ–¯å·´è¾¾", type: "1", hid: 87, newType: "æˆ˜å£«" },
    {
        id: 50001,
        name: "å¹½èƒ½åˆºå®¢",
        type: "2",
        hid: 71,
        newType: "åˆºå®¢",
    },
    { id: 72001, name: "çŽ„ç©¹å¤©å¸", type: "3", hid: 85, newType: "æ³•å¸ˆ" },
    { id: 76001, name: "å¤©è“¬å…ƒå¸…", type: "1", hid: 86, newType: "å¦å…‹" },
    {
        id: 159001,
        name: "å®‰å…¹â€¢ä¹Œå°”â€¢æ­",
        type: "3",
        hid: 83,
        newType: "æ³•å¸ˆ",
    },
    {
        id: 126001,
        name: "æ—¶å…‰å®ˆæŠ¤è€…",
        type: "3",
        hid: 84,
        newType: "æ³•å¸ˆ",
    },
    { id: 140001, name: "åœ£æžªä½¿", type: "2", hid: 82, newType: "å°„æ‰‹" },
    { id: 25001, name: "çŽ„æ­¦", type: "1", hid: 76, newType: "å¦å…‹" },
    { id: 11001, name: "ç‹‚è å¥³çŽ‹", type: "3", hid: 81, newType: "æ³•å¸ˆ" },
    { id: 47001, name: "æœéƒ¨åŠè—", type: "2", hid: 74, newType: "åˆºå®¢" },
    { id: 15001, name: "èš©å°¤", type: "1", hid: 79, newType: "å¦å…‹" },
    { id: 84001, name: "ç™½è¢å·«å¸ˆ", type: "3", hid: 73, newType: "æ³•å¸ˆ" },
    { id: 134001, name: "èŠ±æœ¨å…°", type: "1", hid: 72, newType: "æˆ˜å£«" },
    { id: 63001, name: "é›…å…¸å¨œ", type: "3", hid: 65, newType: "æ³•å¸ˆ" },
    { id: 38001, name: "å¸é©¬æ‡¿", type: "3", hid: 75, newType: "æ³•å¸ˆ" },
    { id: 86001, name: "å­™å°šé¦™", type: "2", hid: 78, newType: "åˆºå®¢" },
    { id: 35001, name: "å›¾å¦å¡è’™", type: "1", hid: 77, newType: "å¦å…‹" },
    { id: 64001, name: "äºšç‘ŸçŽ‹", type: "2", hid: 69, newType: "æˆ˜å£«" },
    { id: 32001, name: "è¯¸è‘›äº®", type: "3", hid: 68, newType: "æ³•å¸ˆ" },
    { id: 93001, name: "æŽæŽ¢èŠ±", type: "2", hid: 70, newType: "å°„æ‰‹" },
    { id: 40001, name: "å®™æ–¯", type: "3", hid: 67, newType: "æ³•å¸ˆ" },
    { id: 108001, name: "å°é¹¿", type: "1", hid: 66, newType: "å¦å…‹" },
    {
        id: 127001,
        name: "ç½—åˆ¹éƒ¡ä¸»",
        type: "2",
        hid: 63,
        newType: "å°„æ‰‹",
    },
    { id: 36001, name: "è²‚è‰", type: "3", hid: 64, newType: "æ³•å¸ˆ" },
    {
        id: 146001,
        name: "ç­ä¸–é­”æ˜Ÿ",
        type: "1",
        hid: 62,
        newType: "æˆ˜å£«",
    },
    { id: 151001, name: "ä½ç½—", type: "2", hid: 61, newType: "åˆºå®¢" },
    {
        id: 130001,
        name: "ç«ç¥žæˆ˜å§¬",
        type: "1",
        hid: 60,
        newType: "å°„æ‰‹",
    },
    { id: 60001, name: "æš´å›è¨ç‰¹", type: "3", hid: 59, newType: "æ³•å¸ˆ" },
    { id: 16001, name: "æ¸©è’‚", type: "1", hid: 58, newType: "å¦å…‹" },
    { id: 150001, name: "é‡å­åšå£«", type: "3", hid: 57, newType: "æ³•å¸ˆ" },
    {
        id: 138001,
        name: "é­…é­”å…¬ä¸»",
        type: "1",
        hid: 56,
        newType: "å¦å…‹",
    },
    { id: 14001, name: "åˆ¤å®˜é’Ÿé¦—", type: "1", hid: 53, newType: "å¦å…‹" },
    { id: 149001, name: "é¾™å½±", type: "2", hid: 54, newType: "æˆ˜å£«" },
    { id: 45001, name: "çŽ‰å…”", type: "2", hid: 55, newType: "å°„æ‰‹" },
    { id: 4001, name: "é»‘æ¡ƒçš‡åŽ", type: "2", hid: 52, newType: "å°„æ‰‹" },
    { id: 2001, name: "ç½ªä¸šç‹‚å± ", type: "1", hid: 51, newType: "å¦å…‹" },
    { id: 82001, name: "å¥³æ­¦ç¥ž", type: "2", hid: 47, newType: "å°„æ‰‹" },
    {
        id: 71001,
        name: "è¥¿é—¨é£žé›ª",
        type: "2",
        hid: 50,
        newType: "åˆºå®¢",
    },
    {
        id: 122001,
        name: "æˆ˜ç¥žé˜¿ç‘žæ–¯",
        type: "1",
        hid: 48,
        newType: "æˆ˜å£«",
    },
    { id: 9001, name: "å¥¥ä¸", type: "1", hid: 42, newType: "æˆ˜å£«" },
    { id: 18001, name: "æ½˜å¤šæ‹‰", type: "3", hid: 49, newType: "æ³•å¸ˆ" },
    { id: 55001, name: "å±±ä¸˜ä¹‹çŽ‹", type: "1", hid: 41, newType: "å¦å…‹" },
    { id: 20001, name: "æš—ç²¾çµ", type: "2", hid: 40, newType: "åˆºå®¢" },
    { id: 59001, name: "è¾¾èŠ¬å¥‡", type: "2", hid: 39, newType: "å°„æ‰‹" },
    { id: 22001, name: "æ ‘ç²¾é•¿è€", type: "3", hid: 46, newType: "å¦å…‹" },
    { id: 65001, name: "å°ä¹”", type: "3", hid: 45, newType: "æ³•å¸ˆ" },
    { id: 70001, name: "å‘¨ç‘œ", type: "3", hid: 44, newType: "æ³•å¸ˆ" },
    { id: 80001, name: "ç‚½ç„°ç«å¥³", type: "3", hid: 36, newType: "æ³•å¸ˆ" },
    { id: 98001, name: "ç¦å¨ƒ", type: "3", hid: 43, newType: "æ³•å¸ˆ" },
    {
        id: 53001,
        name: "ç‰›å¤´äººé…‹é•¿",
        type: "1",
        hid: 37,
        newType: "å¦å…‹",
    },
    { id: 2001, name: "å­™æ‚Ÿç©º", type: "2", hid: 38, newType: "æˆ˜å£«" },
    { id: 1001, name: "å…«å²å¤§è›‡", type: "1", hid: 34, newType: "æˆ˜å£«" },
    { id: 9001, name: "åœ£å¥³è´žå¾·", type: "3", hid: 35, newType: "æ³•å¸ˆ" },
    {
        id: 101001,
        name: "ç»¯é›¨å‰‘æ˜Ÿ",
        type: "2",
        hid: 26,
        newType: "æˆ˜å£«",
    },
    { id: 13001, name: "é¡¹ç¾½", type: "2", hid: 9, newType: "æˆ˜å£«" },
    { id: 17001, name: "å¿˜å·å·«å¥³", type: "3", hid: 20, newType: "æ³•å¸ˆ" },
    { id: 33001, name: "äº”å½©ç¥žçŸ³", type: "1", hid: 7, newType: "å¦å…‹" },
    { id: 67001, name: "æŽå…ƒéœ¸", type: "1", hid: 21, newType: "æˆ˜å£«" },
    { id: 7001, name: "çº¢ç‚ŽåŒåˆƒ", type: "1", hid: 28, newType: "å¦å…‹" },
    { id: 51001, name: "æ³¢å¡žå†¬", type: "3", hid: 24, newType: "æ³•å¸ˆ" },
    { id: 34001, name: "å…³ç¾½", type: "1", hid: 18, newType: "æˆ˜å£«" },
    { id: 77001, name: "å†°é›ªå¥³çŽ‹", type: "3", hid: 4, newType: "æ³•å¸ˆ" },
    { id: 8001, name: "ç”µå…‰ä¾ ", type: "2", hid: 31, newType: "æˆ˜å£«" },
    { id: 107001, name: "ç‹¼çŽ‹", type: "1", hid: 17, newType: "æˆ˜å£«" },
    { id: 30001, name: "é‡‘ä¹Œ", type: "2", hid: 16, newType: "å°„æ‰‹" },
    { id: 37001, name: "èµµäº‘", type: "2", hid: 1, newType: "æˆ˜å£«" },
    { id: 9001, name: "çŒŽé­”äºº", type: "2", hid: 23, newType: "å°„æ‰‹" },
    { id: 39001, name: "å•å¸ƒ", type: "1", hid: 14, newType: "å¦å…‹" },
    { id: 61001, name: "å«¦å¨¥", type: "3", hid: 8, newType: "æ³•å¸ˆ" },
    { id: 46001, name: "ç†ŠçŒ«æ­¦åƒ§", type: "1", hid: 30, newType: "å¦å…‹" },
    { id: 85001, name: "é˜¿æ³¢ç½—", type: "1", hid: 29, newType: "æˆ˜å£«" },
    { id: 9001, name: "å¼ é£ž", type: "1", hid: 10, newType: "å¦å…‹" },
    { id: 96001, name: "è¶…èƒ½ä¼é¹…", type: "2", hid: 3, newType: "å°„æ‰‹" },
    { id: 68001, name: "èµ¤èŽ²çµä»™", type: "2", hid: 13, newType: "æˆ˜å£«" },
    {
        id: 106001,
        name: "å¹»å¡é­”å¥³",
        type: "3",
        hid: 22,
        newType: "æ³•å¸ˆ",
    },
    { id: 2001, name: "å°é¾™å¥³", type: "2", hid: 6, newType: "æˆ˜å£«" },
    { id: 56001, name: "åœ°ç‹±ç«", type: "1", hid: 15, newType: "å¦å…‹" },
    { id: 79001, name: "åŽç¾¿", type: "2", hid: 12, newType: "å°„æ‰‹" },
    { id: 8001, name: "æš—æœˆçŒŽæ‰‹", type: "2", hid: 19, newType: "å°„æ‰‹" },
    { id: 94001, name: "åŸƒåŠè‰³åŽ", type: "3", hid: 27, newType: "æ³•å¸ˆ" },
    { id: 83001, name: "ç²¾çµçŽ‹å­", type: "2", hid: 32, newType: "å°„æ‰‹" },
    { id: 95001, name: "è‚å°å€©", type: "3", hid: 11, newType: "æ³•å¸ˆ" },
    { id: 97001, name: "å¾·å¤æ‹‰", type: "3", hid: 25, newType: "æ³•å¸ˆ" },
    { id: 73001, name: "é¾™éª‘å£«", type: "1", hid: 33, newType: "å°„æ‰‹" },
];
export default HeroesData;
