const ItemData2 = [
    {
        id: 12517,
        name: "RECOVERY RING",
        type: "3",
        img: "12517.png",
        prop: ["Health Regen +6s per second"],
        effect: [""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10107,
        name: "PHANTOM CORSET",
        type: "1",
        img: "10107.png",
        prop: ["Agility +6"],
        effect: ["Unique Passive: recovers 5 Health with each attack"],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10011,
        name: "HASTE GLOVES",
        type: "1",
        img: "10011.png",
        prop: ["Attack Speed +15"],
        effect: [""],
        prize: 450,
        lvl: 1,
    },
    {
        id: 10012,
        name: "LEECH MASK",
        type: "1",
        img: "10012.png",
        prop: [""],
        effect: ["Unique Passive: Physical Life Steal +15%"],
        prize: 900,
        lvl: 1,
    },
    {
        id: 10034,
        name: "ATTACK TALONS",
        type: "1",
        img: "10034.png",
        prop: ["Damage +10"],
        effect: [""],
        prize: 500,
        lvl: 1,
    },
    {
        id: 10036,
        name: "SPIKED CLUB",
        type: "1",
        img: "10036.png",
        prop: ["Damage +10", "Velocidad de ataque +15"],
        effect: [""],
        prize: 900,
        lvl: 1,
    },
    {
        id: 10037,
        name: "FLAMING CLAYMORE",
        type: "1",
        img: "10037.png",
        prop: ["Damage +21"],
        effect: [""],
        prize: 1400,
        lvl: 2,
    },
    {
        id: 125011,
        name: "ALABARDA DE PLATA",
        type: "1",
        img: "125011.png",
        prop: ["Damage +25"],
        effect: ["Atributo- Daño puro I: el 12% del daño de los atques normales y de las habilidades fisicas se convierte en daño puro.",],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 125121,
        name: "GARRA DE LA MUERTE",
        type: "1",
        img: "125121.png",
        prop: ["Damage +40, Fuerza +16"],
        effect: ["Unique Passive -Combinable- conjuracion rapida III: reduce el enfriamiento de las habilidades un 15% (limite 40%)"],
        prize: 5000,
        lvl: 5,
    },
    {
        id: 10110,
        name: "DEMON BLADE",
        type: "1",
        img: "10110.png",
        prop: ["Damage +50"],
        effect: [""],
        prize: 2400,
        lvl: 2,
    },
    {
        id: 10118,
        name: "QUICKENING GEM",
        type: "1",
        img: "10118.png",
        prop: ["Attack Speed +40"],
        effect: [""],
        prize: 2000,
        lvl: 2,
    },
    // {
    //     id: 10122,
    //     name: "Corazon de Jade",
    //     type: "1",
    //     img: "10122.jpg",
    //     prop: ["Health +250", "Mana +200"],
    //     effect: [
    //         "Unique Passive: Spell Resist +20",
    //         "Active Ability - Immunity: Activate to become immune to stun, slow and trap effects. Lasts 3.5s for melee heroes and 2.5s for ranged heroes.",
    //         "Mana Cost: 50, Cooldown: 55s",
    //     ],
    //     prize: 2750,
    //     lvl: 3,
    // },
    {
        id: 10035,
        name: "DEVORA ALMAS",
        type: "1",
        img: "10035.png",
        prop: ["Damage +30"],
        effect: [
            "Unique Passive Robo de vida (fis)+12%",
            "Unique Passive Cada remate del enemigo otorga 4 p. de daño y un 0,5% de robo de vida (fis).Se acumula hasta 10 veces y desaparece si mueres.",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10062,
        name: "CRIPPLING PIERCER",
        type: "1",
        img: "10062.png",
        prop: ["Strength +16", "Damage +10"],
        effect: [
            "Unique Passive: Demon Hack I: Grants each attack 15% of chance to slow enemy's Attack Speed by 20 points and Movement Speed by 20% for 3s.",
        ],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10066,
        name: "SWIFT SPEAR",
        type: "1",
        img: "10066.png",
        prop: ["Agility +16", "Attack Speed +20"],
        effect: ["Attribute: Travel: Movement Speed +10%"],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10067,
        name: "SAVAGE MASK",
        type: "1",
        img: "10067.png",
        prop: ["Damage +18"],
        effect: [
            "Unique Passive: Physical Life Steal +15%",
            "Unique Passive - Savagery: Attacking an enemy hero unit grants 60 Movement Speed for melee heroes and 25 Movement Speed for ranged heroes. Lasts 2s.",
        ],
        prize: 2100,
        lvl: 2,
    },
    {
        id: 10070,
        name: "SCORCHING KNIFE",
        type: "1",
        img: "10070.png",
        prop: ["Damage +30", "Attack Speed +15"],
        effect: [
            "Unique Passive Each basic attack deals magic damage and burns 20 of target's Mana.",
        ],
        prize: 2500,
        lvl: 3,
    },
    {
        id: 125000,
        name: "HOJA SOMBRIA",
        type: "1",
        img: "125000.png",
        prop: ["Damage +30"],
        effect: [
            "Unique Passive cada ataque basico reduce la armadura del objetivo en 30p. durante 5s. No se acumula",
        ],
        prize: 2550,
        lvl: 3,
    },
    {
        id: 10115,
        name: "EXECUTIONER'S CUT",
        type: "1",
        img: "10115.png",
        prop: ["Damage +60"],
        effect: [
            "Unique Passive - Fast Casting III: Cooldown Reduction +15% (Max 40%)",
            "Unique Passive - Physical Life Steal +25%",
            "Unique Passive - Soul Eater (Offense): Each enemy unit last hit grants 5 points of Attack Damage and 1% Physical Life Steal. Max stack is 10. Effect disappears upon death. (Inherits stacks from Souleater Sword)",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 10125,
        name: "DECIMATION MACE",
        type: "1",
        img: "10125.png",
        prop: ["Strength +10", "Attack +30", "Health +300"],
        effect: [
            "Unique Passive: Spell Resist +15",
            "Unique Passive - Heavy Strike: 25% of chance to Stun for 0.5s on melee basic attacks; 10% of chance to Stun for 0.5s on ranged basic attacks. Deals 50 points of on-hit physical damage.",
            "Unique Passive - Exorcism I: If your Health is below 35% after taking magical damage, you take 20% less magical damage for 4s, cooldown: 4s",
            "Setting Sun: Deals 120 plus 8% Target's Max Health magical damage to all enemy units in the nearby area, causing Movement Slow by 70% and reducing their damage output by 30%, lasts 1.5s. Cast Range: 450",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 10127,
        name: "SHATTERING SPIKE",
        type: "1",
        img: "10127.png",
        prop: ["Damage +75"],
        effect: [
            "Attribute - Pure Damage II: Transfers 30% of damage of your attacks and physical abilities into Pure Damage.",
        ],
        prize: 5100,
        lvl: 5,
    },
    {
        id: 10047,
        name: "BACULO DE ORO",
        type: "1",
        img: "10047.png",
        prop: ["Damage +81", "Attack Speed +10"],
        effect: [
            "Unique Passive - Precision Strike II: 75% of chance that your attacks will not miss.",
            "Unique Passive - Head Smack: Each attack deals 4% of target's Max Health magical damage.",
        ],
        prize: 5300,
        lvl: 5,
    },
    {
        id: 10049,
        name: "MONARCA DE JADE",
        type: "1",
        img: "10049.png",
        prop: ["Agility +30", "Damage +45", "Attack Speed +40"],
        effect: [
            "Unique Passive: Dodge +35%",
            "Attribute - Travel I: Movement Speed +10%",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 10051,
        name: "MARTILLO DEL GIGANTE",
        type: "1",
        img: "10051.png",
        prop: ["Strength +10", "Damage +30"],
        effect: [
            "Unique Passive - Heavy Strike: Grants each attack 25% of chance to stun the target for 0.5s for melee heroes and 10% chance to stun the target for 0.5s for ranged heroes. Both heroes deal an extra 50 points of damage.",
        ],
        prize: 3100,
        lvl: 3,
    },
    {
        id: 10053,
        name: "HACHA DEL METAMORFICO",
        type: "1",
        img: "10053.png",
        prop: ["Agility +18", "Damage +30", "Attack Speed +20"],
        effect: [
            "Attribute: Travel I: Movement Speed +10%",
            "Active Ability: Shapeshift: Activate to create 1 illusion of your hero that last 10s. Illusions deal 75%/50% melee/ranged damage and take 200%/250% melee/ranged damage. Cooldown: 30s",
        ],
        prize: 4250,
        lvl: 4,
    },
    {
        id: 10058,
        name: "ESPADA GEMELAS",
        type: "1",
        img: "10058.png",
        prop: ["Strength +16", "Agility +16", "Damage +25", "Attack Speed +25"],
        effect: [
            "Attribute: Travel I: Movement Speed: +12%",
            "Unique Passive - Demon Hack II: Grants each attack 30% chance to slow enemy's 20 Attack Speed and 20% of Movement Speed for melee heroes, or 35 Attack Speed and 35% Movement Speed for ranged heroes. Last 3s",
        ],
        prize: 4300,
        lvl: 4,
    },
    {
        id: 10065,
        name: "ESPINA DEL INFIERNO",
        type: "1",
        img: "10065.png",
        prop: ["Damage +60"],
        effect: [
            "Unique Passive - Fast Casting II: Reduces abilities cooldown by 10%.",
            "Unique Passive - Thorn Slash II: Your attacks reduce target's armor by 30 for 5s. (Can be stacked 3 time)",
        ],
        prize: 5300,
        lvl: 5,
    },
    {
        id: 10068,
        name: "ESPADA INFLAMABLE",
        type: "1",
        img: "10068.png",
        prop: ["Agility +20", "Damage +36", "Attack Speed +35"],
        effect: [
            "Unique Passive - Scorch II: Each basic attack burns 40 points of Mana on targets and deals magical damage.",
            "Attribute - Travel I: Movement Speed +10%",
            "Active Ability - Body Break:Immediately deals 250 + Agility x2 magical damage to the target and slow 30% movement speed for 3s",
        ],
        prize: 5800,
        lvl: 5,
    },
    {
        id: 10059,
        name: "CAPUCHA DEMONIACA",
        type: "3",
        img: "10059.png",
        prop: ["Strength +30", "Armor +30", "Health Regen +10"],
        effect: [
            "Unique Passive Robo de vida(fisica):+25% ",
            "ACTIVA-VAMPIRISMO: Activala para obtener +125% de robo de vida (fisica) adicional durante 3s. enfriamiento:45s costo de mana:50 ",
        ],
        prize: 5600,
        lvl: 5,
    },
    {
        id: 10237,
        name: "CAÑON DIVINO",
        type: "1",
        img: "10237.png",
        prop: ["Damage +100"],
        effect: [
            "Unique Passive: Damage +20%",
            "Unique Passive: Increases critical damage to 250%",
        ],
        prize: 5750,
        lvl: 5,
    },
    {
        id: 10272,
        name: "MASCARA DEMONIACA",
        type: "1",
        img: "10272.png",
        prop: [
            "Damage +45",
            "Attack Speed +25",
            "Health +250",
            "All Attributes +10",
        ],
        effect: [
            "Unique Passive - Physical Life Steal +20%",
            "Unique Passive - Savagery II: After attacks an enemy hero, increases 90 Movement Speed and reduces target's 30% Movement Speed for 2s for melee heroes, or increases 40 and reduces 12% for ranged heroes.",
        ],
        prize: 5500,
        lvl: 5,
    },
    {
        id: 10108,
        name: "EMBLEMA DEL PROFETA",
        type: "2",
        img: "10108.png",
        prop: ["Intelligence +6", "Mana Regen +25%"],
        effect: ["", ""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10071,
        name: "VARITA DE LA CELERIDAD",
        type: "2",
        img: "10071.png",
        prop: [
            "Intelligence +16",
            "Spell Power +40",
            "Health Regen +5",
            "Mana Regen +100%",
        ],
        effect: [
            "Unique Passive - Fast Casting IV: Reduces abilities cooldown by 20%",
            "Attribute - Travel: Movement Speed +10%",
        ],
        prize: 4000,
        lvl: 4,
    },
    {
        id: 10113,
        name: "MANA PEARL",
        type: "2",
        img: "10113.png",
        prop: ["Mana +150"],
        effect: ["", ""],
        prize: 450,
        lvl: 1,
    },
    {
        id: 10116,
        name: "SORCERER'S GEM",
        type: "2",
        img: "10116.png",
        prop: ["Mana Regen +50%"],
        effect: ["", ""],
        prize: 500,
        lvl: 1,
    },
    {
        id: 12303,
        name: "AMPLIFICATION RING",
        type: "2",
        img: "12303.png",
        prop: ["Spell Power +15"],
        effect: ["", ""],
        prize: 900,
        lvl: 1,
    },
    {
        id: 12311,
        name: "ANILLO DIABOLICO",
        type: "2",
        img: "12311.png",
        prop: ["Spell Power +30"],
        effect: ["Unique Passive reduce el enfriamiento de las habilidades un 10% (limite:40%)"],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 10103,
        name: "POWER ROD",
        type: "2",
        img: "10103.png",
        prop: ["Intelligence +16", "Spell Power +25", "Mana Regen +50%"],
        effect: ["", ""],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10104,
        name: "REGEN BEAD",
        type: "2",
        img: "10104.png",
        prop: ["Health Regen +5", "Mana Regen +75%"],
        effect: [
            "Unique Passive - Fast Casting I: Reduces abilities cooldown by 5%",
        ],
        prize: 1750,
        lvl: 2,
    },
    {
        id: 10123,
        name: "CHRONOS CROWN",
        type: "2",
        img: "10123.png",
        prop: ["Health +300", "Mana +250", "Spell Power +40"],
        effect: [
            "Unique Passive - Chronos Power: Increases 60 Health, 60 Mana and 6 Spell Power every minute. The maximum is 300 Health, 300 Mana and 30 Spell.",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10251,
        name: "MAGIC SUCKER",
        type: "2",
        img: "10251.png",
        prop: ["Intelligence +10", "Spell Power +35"],
        effect: ["Unique Passive: Magical Life Steal +20%"],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 12304,
        name: "ENHANCEMENT MASK",
        type: "2",
        img: "12304.png",
        prop: ["Spell Power +30"],
        effect: ["", ""],
        prize: 1500,
        lvl: 2,
    },
    {
        id: 12306,
        name: "MAGIC WARHAMMER",
        type: "2",
        img: "12306.png",
        prop: ["Mana +200", "All Attributes +5"],
        effect: [
            "Unique Passive - Fast Casting II: Reduces abilities cooldown by 10%",
            "Unique Passive - Charge I: After ability cast, increases base damage by 100% in next attack, auto cooldown is 3s.",
        ],
        prize: 2400,
        lvl: 2,
    },
    {
        id: 12314,
        name: "WIZARD'S PRISM",
        type: "2",
        img: "12314.png",
        prop: ["Health +150", "Mana +150", "Spell Power +20"],
        effect: [
            "Unique Passive - Break Spell I: Reduces 8 Spell Resist for all enemy units in a 1200 radius.",
        ],
        prize: 2050,
        lvl: 2,
    },
    {
        id: 10083,
        name: "GOD HAND",
        type: "2",
        img: "10083.png",
        prop: ["Intelligence +15", "Spell Power +40"],
        effect: [
            "Active Ability - God Hand: Activates to emit a powerful burst to a target enemy unit, dealing 400 magical damage. Every 1 Spell Power increases 1 magical damage of God Hand.",
        ],
        prize: 3500,
        lvl: 3,
    },
    {
        id: 12509,
        name: "CRYSTAL HOOK",
        type: "2",
        img: "12509.jpg",
        prop: [
            "Health +350",
            "Intelligence +20",
            "Spell Power +60",
            "Mana Regen +50%",
        ],
        effect: [
            "Unique Passive - Slow: Casting abilities on enemies can also slow their movement speed with this Scepter. Single Spells slow 40% movement speed for 1.5s, while AOE Spells for 1s. Continuous or multi-step Spells slow 20% movement speed for 1s. Gear abilities cannot trigger this effect",
        ],
        prize: 4500,
        lvl: 4,
    },
    {
        id: 10228,
        name: "FROZEN SHARD",
        type: "2",
        img: "10228.png",
        prop: [
            "Intelligence +25",
            "All Attributes +10",
            "Mana Regen +100%",
            "Spell Power +40",
        ],
        effect: [
            "Active Ability - Frozen: Activates to freeze a target enemy hero for 0.5. Afterwards, slows its 40% movement speed for 3s. (Every 40 Intelligence increases 0.2s freezing duration).",
        ],
        prize: 5675,
        lvl: 5,

    },
    {
        id: 12310,
        name: "DEMON DIADEM",
        type: "2",
        img: "12310.png",
        prop: ["All Attributes +10", "Spell Power +50", "Mana +300"],
        effect: [
            "Unique Passive - Fast Casting Ⅲ: CD Reduction: 15%",
            "Unique Passive - Charge II: After casting, gain 75 (100% Spell Power) magical damage bonus to next attack, with 3s cooldown for the effect.",
        ],
        prize: 5200,
        lvl: 5,
    },
    {
        id: 12312,
        name: "CURSED URN",
        type: "2",
        img: "12312.png",
        prop: ["Spell Power +60", "Health Regen +5", "Mana Regen +100%"],
        effect: [
            "Unique Passive - Fast Casting IV: Reduces abilities cooldown by 20%",
            "Unique Passive - Curse: Magical damage abilities curse the enemies, dealing 6% of target's current Health in magical damage for 3s. Can be triggered again after 3s.",
        ],
        prize: 5550,
        lvl: 5,
    },
    {
        id: 12313,
        name: "ALCHEMIST'S ORB",
        type: "2",
        img: "12313.png",
        prop: ["Health +250", "Mana +200", "Spell Power +50"],
        effect: [
            "Unique Passive - Break Spell II: Reduces 15 Spell Resist for all enemy units in a 1200 radius.",
        ],
        prize: 4000,
        lvl: 4,
    },
    {
        id: 10072,
        name: "PHARAOH'S SHROUD",
        type: "2",
        img: "10072.png",
        prop: ["Intelligence +27", "Spell Power +30", "Armor +90"],
        effect: [
            "Unique Passive - Shifting Sands: Reduce Attack Speed of all enemy units in 1000 radius by 25",
            "Active Ability - Pharaoh's Shroud: Your hero cannot move but summons a Pharaoh's Coffin that absorbs up to (2000+1.5*AP) damage for 3s. When the shield is used up, immobility will be cancelled.",
        ],
        prize: 4700,
        lvl: 4,
    },
    {
        id: 12305,
        name: "CONVERSION STAFF",
        type: "2",
        img: "12305.png",
        prop: ["Spell Power +60"],
        effect: ["Unique Passive - Mana Spring: Spell Power increases by 35%"],
        prize: 4200,
        lvl: 4,
    },
    {
        id: 10095,
        name: "VITALITY BELT",
        type: "5",
        img: "10095.png",
        prop: ["All Attributes +3"],
        effect: ["", ""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10106,
        name: "KNIGHT'S WRISTGUARD",
        type: "3",
        img: "10106.png",
        prop: ["Strength +6", "Health Regen +2"],
        effect: ["", ""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10111,
        name: "LIFE PEARL",
        type: "3",
        img: "10111.png",
        prop: ["Health +200"],
        effect: ["", ""],
        prize: 900,
        lvl: 1,
    },
    {
        id: 10112,
        name: "REJUVENATION PEARL",
        type: "3",
        img: "10112.png",
        prop: ["Health +200", "Mana +150"],
        effect: ["", ""],
        prize: 1200,
        lvl: 1,
    },
    {
        id: 10017,
        name: "CHARMED CLOAK",
        type: "3",
        img: "10017.png",
        prop: ["Attribute: Spell Resist +10"],
        effect: ["", ""],
        prize: 500,
        lvl: 1,
    },
    {
        id: 10019,
        name: "EVASION RUNE",
        type: "3",
        img: "10019.png",
        prop: ["Attribute: Dodge chance +15%"],
        effect: ["", ""],
        prize: 1000,
        lvl: 1,
    },
    {
        id: 10042,
        name: "PLATEMAIL",
        type: "3",
        img: "10042.png",
        prop: ["Armor +25"],
        effect: ["", ""],
        prize: 450,
        lvl: 1,
    },
    {
        id: 10087,
        name: "DIVINE SHIELD",
        type: "3",
        img: "10087.png",
        prop: ["All Attributes +6", "Armor +25"],
        effect: [
            "Unique Passive - Divine Light: Grants 4 Health Regen to all allies in a 1000 radius",
            "Active Ability - Heal I: Activate to restore 250 Health to all allies in a 750 radius, while increasing their Armor by 12 for 15s. Mana Cost: 150. Cooldown: 30s",
        ],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10120,
        name: "GIANT AXE",
        type: "3",
        img: "10120.png",
        prop: ["Strength +25", "Health Regen +10"],
        effect: ["", ""],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 12505,
        name: "GARRAS ESPECTRALES",
        type: "1",
        img: "12505.jpg",
        prop: ["Damage +30"],
        effect: [
            "Unique Passive - Fast Casting II: Reduces abilities cooldown by 10%",
            "",
        ],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 12506,
        name: "ANILLO DIABOLICO",
        type: "3",
        img: "12506.jpg",
        prop: ["Spell Power +30"],
        effect: [
            "Unique Passive - Fast Casting II: Reduces abilities cooldown by 10%",
            "",
        ],
        prize: 1800,
        lvl: 2,
    },
    {
        id: "125070",
        name: "VIGOR DE LUZ",
        type: "3",
        img: "125070.png",
        prop: ["Health +250", "Health Regen +5"],
        effect: [
            "Unique Passive - Scorch I: Scorches nearby enemies, dealing 20 magical damage per second. (Deals 100% damage to troops and jungle creatures)",
            "",
        ],
        prize: 1850,
        lvl: 2,
    },
    // {
    //     id: 12508,
    //     name: "DEMONIC COWL",
    //     type: "3",
    //     img: "12508.jpg",
    //     prop: ["Strength +30", "Armor +30", "Health Regen: +10"],
    //     effect: [
    //         "Unique Passive - Life Steal: Activates to gain 125% bonus Physical Life Steal for 3s. Cooldown: 45s Mana Cost: 50",
    //         "",
    //     ],
    //     prize: 5600,
    //     lvl: 5,
    // },
    {
        id: 10271,
        name: "CORAZON DE JADE",
        type: "3",
        img: "10271.png",
        prop: ["Health +250", "Mana +200"],
        effect: [
            "Unique Passive  +20 Resistencia a hechizos",
            "Active Ability Activala para volverte inmune a los efectos de aturdimiento, ralentizacion y trampa. Dura 3.5s para heroes cuerpo a cuerpo y 2.5 para heroes a distancia",
        ],
        prize: 2750,
        lvl: 3,
    },
    {
        id: 10004,
        name: "ENCHANTED ORB",
        type: "3",
        img: "10004.png",
        prop: ["Health +300", ""],
        effect: [
            "Unique Passive: Spell Resist +15",
            "Exorcism I: If your Health is lower than 35% by taking magical damage, further magical damage is reduced by 20% for 4s. Auto Cooldown is 30s.",
        ],
        prize: 2100,
        lvl: 2,
    },
    {
        id: 12308,
        name: "PARASITE SEED",
        type: "3",
        img: "12308.png",
        prop: ["Health +400", "Health Regen +3"],
        effect: [
            "Unique Passive - Soul Eater (Defense): Each last hit on an enemy unit grants 7 Health and 0.3 Health Regen. . Killing troops and jungle creatures adds 1 stack. Last hits on an enemy hero unit adds 10 stacks. Max stack: 50.",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10033,
        name: "PERLA DEL CIELO",
        type: "3",
        img: "10033.png",
        prop: ["All Attributes +10", ""],
        effect: ["", ""],
        prize: 2100,
        lvl: 2,
    },
    {
        id: 10044,
        name: "MITHRIL VEST",
        type: "3",
        img: "10044.png",
        prop: ["Armor +60"],
        effect: ["", ""],
        prize: 1400,
        lvl: 2,
    },
    {
        id: 10076,
        name: "RETRIBRUTION MAIL",
        type: "3",
        img: "10076.png",
        prop: ["Strength +9", "Agility +9", "Damage +15"],
        effect: [
            "Unique Passive - Revenge: Reflects 30% physical damage and 15% magical damage. Reflected damage is treated as real damage.",
        ],
        prize: 2300,
        lvl: 2,
    },
    {
        id: 10077,
        name: "ENERGY DIAMOND",
        type: "3",
        img: "10077.png",
        prop: [
            "Health +450",
            "Mana +400",
            "Health Regen +3",
            "Mana Regen +50%",
        ],
        effect: [
            "Unique Passive - Fast Casting Ⅱ: Reduces abilities cooldown by 10%",
        ],
        prize: 3300,
        lvl: 3,
    },
    {
        id: 10097,
        name: "FORCEFIELD JEWEL",
        type: "3",
        img: "10097.png",
        prop: ["Health +600", "Armor +35"],
        effect: [
            "Unique Passive: Spell Resist +15",
            "Active Ability - Crystal Guardian: Increases Spell Resist by 20 for 15s for all allies within a 700 radius.",
        ],
        prize: 5425,
        lvl: 5,
    },
    {
        id: 10257,
        name: "FUERZA DE ACERO",
        type: "3",
        img: "10257.png",
        prop: ["Armor +90"],
        effect: [
            "Unique Passive: Dodge +30%",
            "Unique Passive - Slow Aura: When attacked, reduces attacker's Movement Speed by 50 and Attack Speed by 30 for 1.5s.",
        ],
        prize: 4250,
        lvl: 4,
    },
    {
        id: 10263,
        name: "PHOENIX HEART",
        type: "3",
        img: "10263.png",
        prop: ["Health +300", "Strength +35"],
        effect: [
            "Unique Passive - Rebirth: Restores 2.5% of max Health per second. If damage is taken from an enemy hero, this ability is disabled for 3s for melee heroes, or 5s for ranged heroes.",
        ],
        prize: 5500,
        lvl: 5,
    },
    {
        id: 12309,
        name: "HEAVEN'S HAMMER",
        type: "3",
        img: "12309.png",
        prop: ["All Attributes +10", "Armor +70", "Mana +300"],
        effect: [
            "Unique Passive - Fast Casting Ⅲ: Reduces abilities cooldown by 15%",
            "Unique Passive - Heaven's Curse: Summons Crashing Thunder after ability is cast, your next attack deals 125% Base Damage as bonus damage, while slowing the target and nearby enemies movement speed by 30% for 2s in a 300 radius. Cooldown: 3s",
        ],
        prize: 5000,
        lvl: 5,
    },
    {
        id: 10030,
        name: "HACHA BARBARA",
        type: "3",
        img: "10030.png",
        prop: ["Strength +10"],
        effect: [""],
        prize: 1000,
        lvl: 1,
    },
    {
        id: 10048,
        name: "SEARING LONGSWORD",
        type: "3",
        img: "10048.png",
        prop: [
            "Health +400",
            "All Attributes +10",
            "Armor +30",
            "Health Regen +8",
        ],
        effect: [
            "Unique Passive - Scorch II: Scorches nearby enemies, dealing 50 + 1% target's Max Health magical damage per second in a 200 radius. (Deals 50% damage to troops and jungle creatures)",
        ],
        prize: 5800,
        lvl: 5,
    },
    {
        id: 10069,
        name: "KING'S ARMOR",
        type: "3",
        img: "10069.png",
        prop: ["Armor +90", "Attack Speed +35"],
        effect: [
            "Unique Passive - Guardian Halo: Increases 30 armor of nearby ally units and buildings in a 1000 radius",
            "Unique Passive - Destructive Pulse: Decreases 30 armor of nearby enemy units and buildings in a 1000 radius.",
            "Unique Passive - Ring Dance: Grants 15 Attack Speed to nearby ally units in a 1000 radius.",
        ],
        prize: 5250,
        lvl: 5,
    },
    {
        id: 10124,
        name: "FROST BITE",
        type: "3",
        img: "10124.png",
        prop: ["Health +300", "Mana +250", "Spell Power +30", "Armor +60"],
        effect: [
            "Active Ability: Activates to emit a freezing wave that deals Intelligence 3x magical damage to enemies in a 600 radius, while slowing their 40% movement speed for 3s.",
            "Cooldown: 30s, Mana Cost: 50",
            "Unique Passive - Break Spell I:Reduces 8 Spell Resist for all enemy units in an 1200 radius.",
        ],
        prize: 4500,
        lvl: 4,
    },
    {
        id: 12316,
        name: "SUMMONING ARMOR",
        type: "3",
        img: "12316.png",
        prop: ["Strength +19", "Agility +19", "Intelligence +10", "Damage +25"],
        effect: [
            "Unique Passive-Revenge: Reflects 30% physical damage and 15% magical damage, all treated as pure damage.",
            "Active Ability-Vengeful Deity: Summon a vengeful deity into you to increase damage reflection to 80% for 3 seconds. Cooldown: 30s, Mana Cost: 40",
        ],
        prize: 4900,
        lvl: 4,
    },
    {
        id: 10265,
        name: "CRYSTAL SHIELD",
        type: "3",
        img: "10265.png",
        prop: ["Health +550", "Mana +250"],
        effect: [
            "Unique Passive: Spell Resist +20",
            "Unique Passive - Iron Wall: Grants 70% of chance to block 80 damage from each incoming attack for melee heroes, or 40 for ranged heroes.",
            "Unique Passive - Exorcism II: If your Health is lower than 35% by taking magical damage, further magical damage is reduced by 35% for 4s. Cooldown: 60s",
        ],
        prize: 4325,
        lvl: 4,
    },
    {
        id: 10085,
        name: "BERSERK LOCKET",
        type: "3",
        img: "10085.png",
        prop: ["All Attributes +3", "Health Regen +6/s’", "Mana Regen +100%"],
        effect: [
            "Unique Passive - Fast Casting Ⅲ：Reduces abilities cooldown by 15%",
            "Active Ability - Ring Dance: Increases 40% Movement Speed and 15 Attack Speed for all allies in a 1000 radius for 4s. Mana Cost: 100. Cooldown: 30s",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10016,
        name: "DASH BOOTS",
        type: "4",
        img: "10016.png",
        prop: ["", ""],
        effect: ["Attribute - Dash: Movement Speed: +50"],
        prize: 500,
        lvl: 1,
    },
    {
        id: 125020,
        name: "BOTAS GUARDIANAS",
        type: "4",
        img: "125020.png",
        prop: ["Armor +35"],
        effect: [
            "Unique Passive Velocidad de movimiento +80", "Probabilidad del 70% de bloquear 30/15 p. de daño para heroes cuerpo a cuerpo/a distancia.",
        ],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 125030,
        name: "BOTAS INSPIRADORAS",
        type: "4",
        img: "125030.png",
        prop: ["+20 Poder de hechizo,Mana Regen +25%"],
        effect: [
            "Unique Passive Reduce el tiempo de reutilizacion de la habilidad en 10%, limitado en 40%",
            "Unique Passive Velocidad de movimiento +80",
        ],
        prize: 1700,
        lvl: 2,
    },
    {
        id: 10100,
        name: "WAR BOOTS",
        type: "4",
        img: "10100.png",
        prop: ["Damage +10", "Attack Speed +25"],
        effect: ["Unique Passive - Dash II: Movement Speed +80"],
        prize: 1450,
        lvl: 2,
    },
    {
        id: 12307,
        name: "STAMINA BOOTS",
        type: "4",
        img: "12307.png",
        prop: ["Health +300"],
        effect: ["Unique Passive - Dash II: Movement Speed: +80"],
        prize: 1600,
        lvl: 2,
    },
    {
        id: 10089,
        name: "Arcana Boots",
        type: "4",
        img: "10089.png",
        prop: ["Mana +250"],
        effect: [
            "Unique Passive - Dash II: Movement Speed: +80",
            "Active Ability - Arcana I: Activates to restore 270 Mana to all allies in a 1000 radius. Cooldown: 30s",
        ],
        prize: 1500,
        lvl: 2,
    },
    {
        id: 10302,
        name: "SPEEDSTER BOOTS",
        type: "4",
        img: "10302.png",
        prop: ["", ""],
        effect: [
            "Unique Passive - Dash III: Movement Speed +90",
            "Grants an aura that increases 6% bonus Movement Speed to all allies in a 1000 radius.",
        ],
        prize: 1600,
        lvl: 2,
    },
    {
        id: 125141,
        name: "MERCY GUARDS",
        type: "4",
        img: "125141.png",
        prop: ["Mana +250", "All Attributes: +6", "Armor: +25"],
        effect: [
            "Unique Passive - Dash II: Movement Speed: +80",
            "Unique Passive - Divine Light: Increase 4 Health Regen of all allies in a 1000 radius.",
            "Active Ability - Heal Heal II: Activates to recover 300 Health and 300 Mana for all allies in a 900 radius, while granting 12 bonus Armor for 15s. Mana Cost: 100, Cooldown: 30s",
        ],
        prize: 4500,
        lvl: 4,

    },
    {
        id: 125161,
        name: "OJO EXORCISTA",
        type: "3",
        img: "125161.png",
        prop: ["Health +550", "Mana +250"],
        effect: [
            "Unique Passive Resistencia a hechizos +35",
            "Los heroes cuerpo a cuerpo se vuelven inmunes a los efectos de aturdimiento durante 3.5s y los heroes a distancia durante 2.5s y su duño magico tomado se reduce en 35%",
        ],
        prize: 4850,
        lvl: 4,
    },
    {
        id: 10300,
        name: "LIFE SPRING",
        type: "3",
        img: "10300.png",
        prop: ["Armor +50"],
        effect: [
            "Unique Passive: Spell Resist +20",
            "Unique Passive: Dodge +25%",
            "Activate to increase max Health by 800 for melee heroes, and 400 for ranged heroes. Lasts 10s. Cooldown: 30s. Mana Cost: 50s.",
        ],
        prize: 4300,
        lvl: 4,

    },
    {
        id: 125131,
        name: "QUICK PULSE",
        type: "2",
        img: "125131.png",
        prop: [
            "Health +350",
            "Mana +300",
            "Spell Power +70",
            "Mana Regen +100%",
        ],
        effect: [
            "Unique Passive: Magical Life Steal +15%",
            "Unique Passive - Fast Casting Ⅳ: Reduces abilities cooldown by 20%",
        ],
        prize: 6450,
        lvl: 5,

    },
    {
        id: 12519,
        name: "DETECTION GEM",
        type: "5",
        img: "12519.png",
        prop: ["All attributes +10"],
        effect: [
            "Unique Passive - Observe II: Whenever an enemy unit in a 1000 radius dies and is not last-hit by you, you gain 10 Coins, recover 10 Health, and 5 Mana..",
        ],
        prize: 2000,
        lvl: 2,
    },
    {
        id: 12520,
        name: "TRUE SIGHT GEM",
        type: "5",
        img: "12520.png",
        prop: ["All attributes +20"],
        effect: [
            "Attribute - ObserverIII You receive an observer guard every 50s, storing up to 3 observer guards.",
            "Loot attributeIII: When an enemy unit dies, not killed by you, within a radius of 1000 around you, you get 15 additional gold and restore 20 health and 10 mana.",
            "Passive Single-Quick Launch II: Reducing skill reuse time by 10%, accumulating up to 40%. Activate Unica-Vision",
            "Unique Passive - Fast Casting Ⅱ: Detecta  Unidades enemigas invisibles dentro de un radio de 1200 a tu alrededor. tiempo de reutilizacion: 40s.",
        ],
        prize: 4000,
        lvl: 4,
    },
    {
        id: 125101,
        name: "ESPADA DEL FENIX",
        type: "1",
        img: "125101.png",
        prop: ["Damage +30"],
        effect: ["Unique Passive: Critical Chance. +15%"],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 125111,
        name: "ESPIRAL DEL CICLON",
        type: "1",
        img: "125111.png",
        prop: ["Damage +25", "Attack Speed +15"],
        effect: [
            "Unique Passive - Precision Strike I: 40% of your attacks will not miss.",
        ],
        prize: 2000,
        lvl: 2,

    },
    // {
    //     id: "k13",
    //     name: "ALABARDA DE PLATA",
    //     type: "1",
    //     img: "k13.jpg",
    //     prop: ["Damage +25"],
    //     effect: [
    //         "Attribute: Pure Damage Transfers 12% of damage of your attacks and physical abilities into Pure Damage.",
    //     ],
    //     prize: 1800,
    //     lvl: 2,
    // },
    // {
    //     id: "k14",
    //     name: "HOJA SOMBRIA",
    //     type: "1",
    //     img: "k14.jpg",
    //     prop: ["Damage +30"],
    //     effect: [
    //         "Unique Passive - Thorn Slash I: Your attacks reduce target's 30 points of Armor for 5s, and cannot be stacked.",
    //     ],
    //     prize: 2550,
    //     lvl: 3,
    // },
    {
        id: 125151,
        name: "DANCER'S GREAVES",
        type: "4",
        img: "125151.png",
        prop: ["All Attributes +3", "Health Regen +6/s", "Mana Regen +100%"],
        effect: [
            "Unique Passive - Dash III: Movement Speed +90",
            "Unique Passive - Fast Casting Ⅲ: Reduces abilities cooldown by 15%.",
            "Unique Passive - Holy Passage: Increases Movement Speed by 8% for all allies within a range of 1000.",
            "Active Ability - Ring Dance: Increases 30% Movement Speed and 15 Attack Speed to all allies in a 1000 radius for 4s. Mana Cost: 100.",
        ],
        prize: 4800,
        lvl: 4,
    },
    {
        id: 12533,
        name: "ZAKAR'S BLIGHT",
        type: "2",
        img: "12533.png",
        prop: ["Spell Power +60", "Attack Speed +35"],
        effect: [
            "Unique Passive - Fast Casting III: Reduces abilities cooldown by 15% (up to 40%)",
            "Attribute - Travel I: Movement Speed +10%",
            "Unique Passive - Blight: Each basic attack deals on-hit 20 + 15% Spell Power magical damage.",
        ],
        prize: 4500,
        lvl: 4,
    },
    {
        id: 12532,
        name: "DOME BREAKER",
        type: "2",
        img: "12532.png",
        prop: ["Intelligence +20", "Spell Power +110", "Mana Regen +100%"],
        effect: [
            "Active - Dome Breaker: Deals 600 magical damage to target enemy hero unit, every 1 Spell Power grants 1 bonus magical damage. Mana Cost: 250. Cooldown: 35s. Cast Range: 850",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 12317,
        name: "CORONETA RESPLANDECIENTE",
        type: "2",
        img: "12317.png",
        prop: ["Health +350", "Mana +250", "Spell Power +70"],
        effect: [
            "Unique Passive reduccion de enfriarse 10%",
            "Unique Passive Corre hacia adelante por 800, evitando terrenos.",
        ],
        prize: 6350,
        lvl: 5,
    },
    // {
    //     id: 12502,
    //     name: "GUARDIAN BOOTS",
    //     type: "4",
    //     img: "12502.jpg",
    //     prop: ["Armor +35"],
    //     effect: [
    //         "Attribute - Dash II: Movement Speed: +80",
    //         "Unique Passive -Iron Wall: Gives 70% chance to block 30/15 damage for melee/ranged.",
    //     ],
    //     prize: 1800,
    //     lvl: 2,
    // },
    // {
    //     id: 12503,
    //     name: "WIZARD BOOTS",
    //     type: "4",
    //     img: "12503.jpg",
    //     prop: ["Spell Power +20"],
    //     effect: [
    //         "Unique Passive - Fast Casting Ⅱ: Reduces abilities cooldown by 10%",
    //         "Unique Passive - Dash II: Movement Speed: +80",
    //     ],
    //     prize: 1800,
    //     lvl: 2,
    // },
    {
        id: 12684,
        name: "COLLAR DE DESPERTAR",
        type: "3",
        img: "12684.png",
        prop: ["All Attributes +25", "Health +150"],
        effect: [
            "Unique Passive Activa las fuerzas latentes mas poderosas de un heroe, otorgandole una posicion ventajosa. ",
        ],
        prize: 5000,
        lvl: 5,

    },
    {
        id: 12321,
        name: "GEMA DE DETECCION ",
        type: "5",
        img: "12321.png",
        prop: ["All Attributes +10"],
        effect: [
            "Reduce el tiempo de reutilizacion de tus guardianes observadoras en 15s. cuando una unidad enemiga muere, no asesinada por ti, dentro de un radio de 1000 a tu alrededor, obtienes 10 de oro adicional y restauras 10 de salud y 5 de mana",
        ],
        prize: 2000,
        lvl: 2,
    },
    // {
    //     id: 12321,
    //     name: "GEMA DE DETECCION ",
    //     type: "5",
    //     img: "12519.png",
    //     prop: ["All Attributes +10"],
    //     effect: [
    //         "Reduce el tiempo de reutilizacion de tus guardianes observadoras en 15s. cuando una unidad enemiga muere, no asesinada por ti, dentro de un radio de 1000 a tu alrededor, obtienes 10 de oro adicional y restauras 10 de salud y 5 de mana",
    //     ],
    //     prize: 2000,
    //     lvl: 2,
    // },
];

export default ItemData2;
