const ItemData2 = [
    {
        id: 12517,
        name: "ANILLO DE RECUPERACIÓN",
        type: "3",
        img: "12517.png",
        prop: ["Regeneración de vida +6 por segundo"],
        effect: [""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10107,
        name: "FAJÍN ESPECTRAL",
        type: "1",
        img: "10107.png",
        prop: ["Agilidad +6"],
        effect: ["Cada ataque restaura 5 p. de vida "],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10011,
        name: "GUANTES DEL ASESINO",
        type: "1",
        img: "10011.png",
        prop: ["Velocidad de ataque +15"],
        effect: [""],
        prize: 450,
        lvl: 1,
    },
    {
        id: 10012,
        name: "MÁSCARA DEL SACRIFICIO",
        type: "1",
        img: "10012.png",
        prop: [""],
        effect: ["Robo de vida física +15%"],
        prize: 900,
        lvl: 1,
    },
    {
        id: 10034,
        name: "GARRAS DE ATAQUE",
        type: "1",
        img: "10034.png",
        prop: ["Daño +10"],
        effect: [""],
        prize: 500,
        lvl: 1,
    },
    {
        id: 10036,
        name: "GARROTE DE PINCHOS",
        type: "1",
        img: "10036.png",
        prop: ["Daño +10, Velocidad de ataque +15"],
        effect: [""],
        prize: 900,
        lvl: 1,
    },
    {
        id: 10037,
        name: "FLORETE LLAMEANTE",
        type: "1",
        img: "10037.png",
        prop: ["Daño +21"],
        effect: [""],
        prize: 1400,
        lvl: 2,
    },
    {
        id: 125011,
        name: "ALABARDA DE PLATA",
        type: "1",
        img: "125011.png",
        prop: ["Daño +25"],
        effect: ["Atributo- Daño puro I: el 12% del daño de los atques normales y de las habilidades fisicas se convierte en daño puro.",],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 125121,
        name: "GARRA DE LA MUERTE",
        type: "1",
        img: "125121.png",
        prop: ["Daño +40, Fuerza +16"],
        effect: ["Combinable- Conjuración rapida III: reduce el enfriamiento de las habilidades un 15% (limite 40%)"],
        prize: 5000,
        lvl: 5,
    },
    {
        id: 10110,
        name: "ESPADA DEL DIABLO",
        type: "1",
        img: "10110.png",
        prop: ["Daño +50"],
        effect: [""],
        prize: 2400,
        lvl: 2,
    },
    {
        id: 10118,
        name: "GEMA DE FURIA",
        type: "1",
        img: "10118.png",
        prop: ["Velocidad de atque +40"],
        effect: [""],
        prize: 2000,
        lvl: 2,
    },
    // {
    //     id: 10122,
    //     name: "Corazon de Jade",
    //     type: "1",
    //     img: "10122.jpg",
    //     prop: ["Health +250", "Mana +200"],
    //     effect: [
    //         "Unique Passive: Spell Resist +20",
    //         "Active Ability - Immunity: Activate to become immune to stun, slow and trap effects. Lasts 3.5s for melee heroes and 2.5s for ranged heroes.",
    //         "Mana Cost: 50, Cooldown: 55s",
    //     ],
    //     prize: 2750,
    //     lvl: 3,
    // },
    {
        id: 10035,
        name: "DEVORA ALMAS",
        type: "1",
        img: "10035.png",
        prop: ["Daño +30"],
        effect: [
            "Combinable: Robo de vida física +12%",
            "Combinable: Devoraalmas (ofensivo): cada remate del enemigo otorga 4 p. de daño y un 0,5% de robo de vida (fis).Se acumula hasta 10 veces y desaparece si mueres.",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10062,
        name: "PERFORACIELOS",
        type: "1",
        img: "10062.png",
        prop: ["Fuerza +16", "Daño +10"],
        effect: [
            "Combinable: Tajo demoníaco I: Los ataques tienen un 15% de probabilidad de reducir la velocidad de ataque del enemigo en 20 p.y la de movimiento un 20% durante 3 s.",
        ],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10066,
        name: "LANZA DEL CREPÚSCULO",
        type: "1",
        img: "10066.png",
        prop: ["Agilidad +16", "Velocidad de ataque +20"],
        effect: ["Atributo: Desplazamiento I: Velocidad de movimiento +10%"],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10067,
        name: "MÁSCARA ESPECTRAL",
        type: "1",
        img: "10067.png",
        prop: ["Daño +18"],
        effect: [
            "Combinable: Robo de vida física +15%",
            "Combinable - Salvajismo I: Los héroes con ataques cuerpo a cuerpo/a distancia obtienen velocidad de movimiento +60/25 tras atacar héroes enemigos. Dura 2 s.",
        ],
        prize: 2100,
        lvl: 2,
    },
    {
        id: 10070,
        name: "CUCHILLO DEL INVOCADOR",
        type: "1",
        img: "10070.png",
        prop: ["Daño +30", "Velocidad de ataque +15"],
        effect: [
            "Combinable: Quemadura I: Cada ataque básico quema 20 p. de maná del objetivo y le inflije la misma cantidad de daño mágico.",
        ],
        prize: 2500,
        lvl: 3,
    },
    {
        id: 125000,
        name: "HOJA SOMBRIA",
        type: "1",
        img: "125000.png",
        prop: ["Daño +30"],
        effect: [
            "Combinable: Corte de espina I: Cada ataque básico reduce la armadura del objetivo en 30 p. durante 5 s. No se acumula.",
        ],
        prize: 2550,
        lvl: 3,
    },
    {
        id: 10115,
        name: "VERDUGO",
        type: "1",
        img: "10115.png",
        prop: ["Daño +60"],
        effect: [
            "Pasiva única - Conjuración Rápida III: 15% Reducción de enfriamiento (máx. 40%)",
            "Pasiva única: +25% Robo de vida (física)",
            "Pasiva única - Deboraalmas (ofensiva): Cada golpe final a un enemigo otorga 5 de daño de ataque y 1% de robo de vida física con un máx. de 10 acumulaciones. El eecto desaparece al morir. (Hereda las acumulaciones de Devoraalmas).",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 10125,
        name: "MARTILLO DEL APOCALIPSIS ",
        type: "1",
        img: "10125.png",
        prop: ["Fuerza +10", "Ataque +30", "Salud +300"],
        effect: [
            "Pasiva única: Resistencia mágica  +15",
            "Pasiva única - 25% probabilidad de aturdir por 0.5 s en ataques básicos cuerpo a cuerpo 10% probabilidad de aturdir por 0.5 s en ataques básicos a distancia. Ataques pesados 50 daño físico al golpear.",
            "Pasiva única - Exorcismo I: Si tu salúd está por debajo de 35% después de recibir daño daño mágico, recibes 20% menos daño mágico durante 4 s. Enfriamiento: 30 s.",
            "Activo - Sol poniente : Otorga 120 más 8% de daño mágico de salúd máxima del objetivo a todas las unidades enemigas en la zona cercana, causando realentización de movimiento en 70% y reducción de daño en 30%, dura 1.5 s. Enfriamiento:45 s. Radio: 450",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 10127,
        name: "PUNTA AFILADA",
        type: "1",
        img: "10127.png",
        prop: ["Daño +75"],
        effect: [
            "Atributo - Daño puro II: el 30% del daño de los ataques normales y de las habilidades físicas se convierte en daño puro.",
        ],
        prize: 5100,
        lvl: 5,
    },
    {
        id: 10047,
        name: "BÁCULO DE ORO",
        type: "1",
        img: "10047.png",
        prop: ["Daño +81", "Velocidad de ataque +10"],
        effect: [
            "Combinable: Golpe preciso II: Los ataques básicos tienen una probabilidad de éxito del 75%.",
            "Combinable: Cabezazo: Los ataques normales infligen el 4% de la vida máxima del enemigo como daño mágico.",
        ],
        prize: 5300,
        lvl: 5,
    },
    {
        id: 10049,
        name: "MONARCA DE JADE",
        type: "1",
        img: "10049.png",
        prop: ["Agilidad +30", "Daño +45", "Velocidad de ataque +40"],
        effect: [
            "Pasiva única: Esquivar +35%",
            "Atributo - Viaje I: velocidad de movimiento +10%",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 10051,
        name: "MARTILLO DEL GIGANTE",
        type: "1",
        img: "10051.png",
        prop: ["Fuerza +10", "Daño +30"],
        effect: [
            "Combinable: Embate potente: Los héroes con ataques cuerpo a cuerpo/a distancia tienen una probabilidad del 25%/10% de infligir un embate potente que aturde durante 0.5 s. Además inflige 50 p. de daño adicional.",
        ],
        prize: 3100,
        lvl: 3,
    },
    {
        id: 10053,
        name: "HACHA DEL METAMORFICO",
        type: "1",
        img: "10053.png",
        prop: ["Agilidad +18", "Daño +30", "Velocidad de ataque +20"],
        effect: [
            "Atributo: Desplazamiento I: velocidad de movimiento +10%",
            "Habilidad activa: Cambio de forma: Actívala para crear 1 ilusión de tu héroe que dura 10 s. Las ilusiones infligen un 75%/50% de daño cuerpo a cuerpo/rango y reciben un 200%/250% de daño cuerpo a cuerpo/rango. Enfriamiento: 30s",
        ],
        prize: 4250,
        lvl: 4,
    },
    {
        id: 10058,
        name: "ESPADA GEMELAS",
        type: "1",
        img: "10058.png",
        prop: ["Fuerza +16", "Agilidad +16", "Daño +25", "Velocidad de ataque +25"],
        effect: [
            "Atributo: Viaje I: Velocidad de movimiento: +12%",
            "Pasiva única - Hachazo demoníaco II: Concede a cada ataque un 30% de probabilidad de ralentizar la Velocidad de ataque del enemigo 20 y la Velocidad de movimiento 20% para héroes cuerpo a cuerpo, o 35 y 35% para héroes a distancia. Últimos 3s",
        ],
        prize: 4300,
        lvl: 4,
    },
    {
        id: 10065,
        name: "ESPINA DEL INFIERNO",
        type: "1",
        img: "10065.png",
        prop: ["Daño +60"],
        effect: [
            "Pasiva única - Lanzamiento rápido II: Reduce el Enfriamiento de habilidades un 10%.",
            "Pasiva única, Tajo de espinas II: Tus ataques reducen la armadura del objetivo en 30 durante 5 s. (Se puede acumular 3 veces).",
        ],
        prize: 5300,
        lvl: 5,
    },
    {
        id: 10068,
        name: "ESPADA INFLAMABLE",
        type: "1",
        img: "10068.png",
        prop: ["Agilidad +20", "Daño +36", "Velocidad de ataque +35"],
        effect: [
            "Pasiva única, Antorcha II: Cada ataque básico quema 40 puntos de Maná de los objetivos e inflige daño mágico.",
            "Atributo - Desplazamiento I: Velocidad de movimiento +10",
            "Habilidad activa - Ruptura corporal:Inflige inmediatamente 250 + Agilidad x2 de daño mágico al objetivo y reduce un 30% la Velocidad de movimiento durante 3 s.",
        ],
        prize: 5800,
        lvl: 5,
    },
    {
        id: 10059,
        name: "CAPUCHA DEMONIACA",
        type: "3",
        img: "10059.png",
        prop: ["Fuerza +30", "Armadura +30", "Regeneración de salud +10"],
        effect: [
            "Pasiva única: Robo de vida(fisica):+25% ",
            "ACTIVA-VAMPIRISMO: Activala para obtener +125% de robo de vida (fisica) adicional durante 3s. enfriamiento:45s costo de mana:50 ",
        ],
        prize: 5600,
        lvl: 5,
    },
    {
        id: 10237,
        name: "CAÑON DIVINO",
        type: "1",
        img: "10237.png",
        prop: ["Daño +100"],
        effect: [
            "Pasiva única: Daño +20",
            "Pasiva única: aumenta el daño crítico un 250%.",
        ],
        prize: 5750,
        lvl: 5,
    },
    {
        id: 10272,
        name: "MASCARA DEMONIACA",
        type: "1",
        img: "10272.png",
        prop: [
            "Daño +45",
            "Velocidad de Ataque +25",
            "Salud +250",
            "Todos los atributos +10",
        ],
        effect: [
            "Pasiva única - Robo de vida física +20%",
            "Pasiva única - Salvajismo II: Tras atacar a un héroe enemigo, aumenta 90 Velocidad de movimiento y reduce 30% la Velocidad de movimiento del objetivo durante 2 s para héroes cuerpo a cuerpo, o aumenta 40 y reduce 12% para héroes a distancia.",
        ],
        prize: 5500,
        lvl: 5,
    },
    {
        id: 10108,
        name: "EMBLEMA DEL PROFETA",
        type: "2",
        img: "10108.png",
        prop: ["Inteligencia +6", "Regeneración de maná +25"],
        effect: ["", ""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10071,
        name: "VARITA DE LA CELERIDAD",
        type: "2",
        img: "10071.png",
        prop: [
            "Inteligencia +16",
            "Poder de Hechizo +40",
            "Regeneración de salud +5",
            "Regeneración de maná +100",
        ],
        effect: [
            "Pasiva única - Lanzamiento rápido IV: Reduce el Enfriamiento de habilidades un 20%",
            "Atributo - Viaje: Velocidad de movimiento +10",
        ],
        prize: 4000,
        lvl: 4,
    },
    {
        id: 10113,
        name: "PERLA DE MAGIA",
        type: "2",
        img: "10113.png",
        prop: ["Maná +150"],
        effect: ["", ""],
        prize: 450,
        lvl: 1,
    },
    {
        id: 10116,
        name: "GEMA DEL HECHICERO",
        type: "2",
        img: "10116.png",
        prop: ["Regeneración de maná +50"],
        effect: ["", ""],
        prize: 500,
        lvl: 1,
    },
    {
        id: 12303,
        name: "ANILLO DE AMPLIFICACIÓN",
        type: "2",
        img: "12303.png",
        prop: ["Poder de Hechizo +15"],
        effect: ["", ""],
        prize: 900,
        lvl: 1,
    },
    {
        id: 12311,
        name: "ANILLO DIABOLICO",
        type: "2",
        img: "12311.png",
        prop: ["Poder de Hechizo +30"],
        effect: ["Pasiva única: reduce el enfriamiento de las habilidades un 10% (limite:40%)"],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 10103,
        name: "BÁCULO DEL MISTERIO",
        type: "2",
        img: "10103.png",
        prop: ["Inteligencia +16", "Poder de hechizo +25", "Regeneración de maná +50%"],
        effect: ["", ""],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10104,
        name: "PERLA DE LA MASACRE",
        type: "2",
        img: "10104.png",
        prop: ["Regeneración de salud +5", "Regeneración de maná +75%"],
        effect: [
            "Unique Passive - Fast Casting I: Reduces abilities cooldown by 5%",
        ],
        prize: 1750,
        lvl: 2,
    },
    {
        id: 10123,
        name: "CORONA DE CRONOS",
        type: "2",
        img: "10123.png",
        prop: ["Salud +300", "Maná +250", "Poder de hechizo +40"],
        effect: [
            "Pasiva única - Poder de Chronos: Aumenta 60 de Vida, 60 de Maná y 6 de Poder de Hechizo cada minuto. El máximo es 300 de Vida, 300 de Maná y 30 de Hechizo.",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10251,
        name: "BÁCULO DE LA LUNA ROJA",
        type: "2",
        img: "10251.png",
        prop: ["Inteligencia +10", "Poder de hechizo +35"],
        effect: ["Pasiva única: Robo de vida mágico +20"],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 12304,
        name: "MÁSCARA MALDITA",
        type: "2",
        img: "12304.png",
        prop: ["Poder de Hechizo +30"],
        effect: ["", ""],
        prize: 1500,
        lvl: 2,
    },
    {
        id: 12306,
        name: "MARTILLO MÁGICO",
        type: "2",
        img: "12306.png",
        prop: ["Maná +200", "Todos los atributos +5"],
        effect: [
            "Pasiva única - Lanzamiento rápido II: Reduce el enfriamiento de las habilidades un 10%",
            "Pasiva única - Carga I: Tras el lanzamiento de la habilidad, aumenta el daño base un 100% en el siguiente ataque, el enfriamiento automático es de 3s.",
        ],
        prize: 2400,
        lvl: 2,
    },
    {
        id: 12314,
        name: "PRISMA DE HECHICERÍA",
        type: "2",
        img: "12314.png",
        prop: ["Salud +150", "Maná +150", "Poder de hechizo +20"],
        effect: [
            "Pasiva única, Romper hechizo I: Reduce 8 Resistencia a hechizos de todas las unidades enemigas en un radio de 1200.",
        ],
        prize: 2050,
        lvl: 2,
    },
    {
        id: 10083,
        name: "DIVINIDAD",
        type: "2",
        img: "10083.png",
        prop: ["Inteligencia +15", "Poder de hechizo +40"],
        effect: [
            "Habilidad activa - Mano de Dios: Se activa para emitir una potente ráfaga a una unidad enemiga objetivo, infligiendo 400 de daño mágico. Cada 1 Poder de Hechizo aumenta 1 daño mágico de Mano de Dios.",
        ],
        prize: 3500,
        lvl: 3,
    },
    {
        id: 12509,
        name: "CETRO DE CRISTAL",
        type: "2",
        img: "12509.jpg",
        prop: [
            "Salud +350",
            "Inteligencia +20",
            "Poder de Hechizo +60",
            "Regeneración de maná +50",
        ],
        effect: [
            "Pasiva única - Ralentización: Al lanzar habilidades a los enemigos, también puedes ralentizar su Velocidad de movimiento con este Cetro. Los hechizos individuales reducen la Velocidad de movimiento un 40% durante 1,5 s, mientras que los hechizos AOE lo hacen durante 1 s. Los hechizos continuos o de varios pasos reducen la Velocidad de movimiento un 20% durante 1 s. Las habilidades de equipo no pueden activar este efecto",
        ],
        prize: 4500,
        lvl: 4,
    },
    {
        id: 10228,
        name: "CETRO CONGELADO",
        type: "2",
        img: "10228.png",
        prop: [
            "Inteligencia +25",
            "Todos los Atributos +10",
            "Regeneración de maná +100%",
            "Poder de hechizo +40",
        ],
        effect: [
            "Habilidad activa - Congelado: Se activa para congelar a un héroe enemigo objetivo durante 0,5 s. Después, ralentiza su velocidad de movimiento un 40% durante 3 s (cada 40 de Inteligencia aumenta la duración de congelación 0,2 s).",
        ],
        prize: 5675,
        lvl: 5,

    },
    {
        id: 12310,
        name: "DIADEMA DEMONÍACA",
        type: "2",
        img: "12310.png",
        prop: ["Todos los atributos +10", "Poder de hechizo +50", "Maná +300"],
        effect: [
            "Pasiva Única - Lanzamiento Rápido Ⅲ: Reducción de CD: 15%",
            "Pasiva única - Carga II: Tras lanzar, obtienes 75 (100% Potencia de hechizo) de bonificación de daño mágico al siguiente ataque, con 3 s de enfriamiento del efecto.",
        ],
        prize: 5200,
        lvl: 5,
    },
    {
        id: 12312,
        name: "URNA DEL DIABLO",
        type: "2",
        img: "12312.png",
        prop: ["Poder de hechizo +60", "Regeneración de salud +5", "Regeneración de maná +100%"],
        effect: [
            "Pasiva única - Lanzamiento rápido IV: Reduce el enfriamiento de las habilidades un 20%",
            "Pasiva única - Maldición: Las habilidades de daño mágico maldicen a los enemigos, infligiendo un 6% de la Vida actual del objetivo en daño mágico durante 3s. Se puede volver a activar al cabo de 3 s.",
        ],
        prize: 5550,
        lvl: 5,
    },
    {
        id: 12313,
        name: "ORBE ARCANO",
        type: "2",
        img: "12313.png",
        prop: ["Salud +250", "Maná +200", "Poder de hechizo +50"],
        effect: [
            "Pasiva única - Romper hechizo II: Reduce 15 Resistencia a hechizos de todas las unidades enemigas en un radio de 1200.",
        ],
        prize: 4000,
        lvl: 4,
    },
    {
        id: 10072,
        name: "SUDERO DEL FARAON",
        type: "2",
        img: "10072.png",
        prop: ["Inteligencia +27", "Poder de hechizo +30", "Armadura +90"],
        effect: [
            "Pasiva única - Arenas movedizas: Reduce la Velocidad de ataque de todas las unidades enemigas en un radio de 1000 en 25",
            "Habilidad Activa - Sudario del Faraón: Tu héroe no puede moverse pero invoca un Ataúd del faraón que absorbe hasta (2000+1.5*AP) de daño durante 3s. Cuando se agote el escudo, se cancelará la inmovilidad.",
        ],
        prize: 4700,
        lvl: 4,
    },
    {
        id: 12305,
        name: "BÁCULO DE LA CONVERSIÓN",
        type: "2",
        img: "12305.png",
        prop: ["Poder de Hechizo +60"],
        effect: ["Pasiva única - Manantial de maná: El poder de hechizo aumenta un 35%."],
        prize: 4200,
        lvl: 4,
    },
    {
        id: 10095,
        name: "BANDA DEL SACERDOTE",
        type: "5",
        img: "10095.png",
        prop: ["Todos los atributos +3"],
        effect: ["", ""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10106,
        name: "BRAZAL DEL CABALLERO",
        type: "3",
        img: "10106.png",
        prop: ["Fuerza +6", "Regeneración de salud +2"],
        effect: ["", ""],
        prize: 600,
        lvl: 1,
    },
    {
        id: 10111,
        name: "PERLA DE LA VIDA ",
        type: "3",
        img: "10111.png",
        prop: ["Salud +200"],
        effect: ["", ""],
        prize: 900,
        lvl: 1,
    },
    {
        id: 10112,
        name: "PERLA DE ESCENCIA",
        type: "3",
        img: "10112.png",
        prop: ["Salud +200", "Maná +150"],
        effect: ["", ""],
        prize: 1200,
        lvl: 1,
    },
    {
        id: 10017,
        name: "MANTO DEL EXORCISMO",
        type: "3",
        img: "10017.png",
        prop: ["Atributo: Resistencia a Hechizos +10"],
        effect: ["", ""],
        prize: 500,
        lvl: 1,
    },
    {
        id: 10019,
        name: "TALISMÁN DE EVASIÓN",
        type: "3",
        img: "10019.png",
        prop: ["Atributo: Probabilidad de esquivar +15"],
        effect: ["", ""],
        prize: 1000,
        lvl: 1,
    },
    {
        id: 10042,
        name: "ARMADURA DEL MERCENARIO",
        type: "3",
        img: "10042.png",
        prop: ["Armadura +25"],
        effect: ["", ""],
        prize: 450,
        lvl: 1,
    },
    {
        id: 10087,
        name: "ESCUDO ANGELICAL",
        type: "3",
        img: "10087.png",
        prop: ["Todos los atributos +6", "Armadura +25"],
        effect: [
            "Pasiva única - Luz divina: Concede 4 de Regeneración de Vida a todos los aliados en un radio de 1000",
            "Habilidad activa - Curación I: Actívala para restaurar 250 puntos de Vida a todos los aliados en un radio de 750, mientras aumentas su Armadura en 12 durante 15 s. Coste de maná: 150. Enfriamiento: 30s",
        ],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 10120,
        name: "ROMPE MONTAÑAS",
        type: "3",
        img: "10120.png",
        prop: ["Fuerza +25", "Regeneración de salud +10"],
        effect: ["", ""],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 12505,
        name: "GARRAS ESPECTRALES",
        type: "1",
        img: "12505.jpg",
        prop: ["Daño +30"],
        effect: [
            "Pasiva única - Lanzamiento rápido II: reduce el enfriamiento de las habilidades un 10%.",
            "",
        ],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 12506,
        name: "ANILLO DIABOLICO",
        type: "3",
        img: "12506.jpg",
        prop: ["Poder de Hechizo +30"],
        effect: [
            "Pasiva única - Lanzamiento rápido II: reduce el enfriamiento de las habilidades un 10%.",
            "",
        ],
        prize: 1800,
        lvl: 2,
    },
    {
        id: "125070",
        name: "VIGOR DE LUZ",
        type: "3",
        img: "125070.png",
        prop: ["Salud +250", "Regeneración de salud +5"],
        effect: [
            "Pasiva única - Ardor I: Achicharra a los enemigos cercanos, infligiendo 20 de daño mágico por segundo. (Inflige un 100% de daño a tropas y criaturas de la jungla).",
            "",
        ],
        prize: 1850,
        lvl: 2,
    },
    // {
    //     id: 12508,
    //     name: "DEMONIC COWL",
    //     type: "3",
    //     img: "12508.jpg",
    //     prop: ["Strength +30", "Armor +30", "Health Regen: +10"],
    //     effect: [
    //         "Unique Passive - Life Steal: Activates to gain 125% bonus Physical Life Steal for 3s. Cooldown: 45s Mana Cost: 50",
    //         "",
    //     ],
    //     prize: 5600,
    //     lvl: 5,
    // },
    {
        id: 10271,
        name: "CORAZON DE JADE",
        type: "3",
        img: "10271.png",
        prop: ["Salud +250", "Maná +200"],
        effect: [
            "Pasiva única:  +20 Resistencia a hechizos",
            "Habilidad Activa: Activala para volverte inmune a los efectos de aturdimiento, ralentizacion y trampa. Dura 3.5s para heroes cuerpo a cuerpo y 2.5 para heroes a distancia",
        ],
        prize: 2750,
        lvl: 3,
    },
    {
        id: 10004,
        name: "ORBE DEL EXORCISTA",
        type: "3",
        img: "10004.png",
        prop: ["Salud +300", ""],
        effect: [
            "Pasiva única: Resistencia a hechizos +15",
            "Exorcismo I: Si tu Vida es inferior al 35% por recibir daño mágico, el daño mágico adicional se reduce un 20% durante 4s. El Enfriamiento automático es de 30s.",
        ],
        prize: 2100,
        lvl: 2,
    },
    {
        id: 12308,
        name: "PERLA SORBEALMAS",
        type: "3",
        img: "12308.png",
        prop: ["Salud +400", "Regeneración de salud +3"],
        effect: [
            "Pasiva única - Devorador de almas (Defensa): Cada último golpe a una unidad enemiga otorga 7 puntos de Vida y 0,3 de Regeneración de Vida. . Matar tropas y criaturas de la jungla añade 1 acumulación. Los últimos golpes a una unidad enemiga añaden 10 acumulaciones. Pila máxima: 50.",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10033,
        name: "PERLA DEL CIELO",
        type: "3",
        img: "10033.png",
        prop: ["Todos los atributos +10", ""],
        effect: ["", ""],
        prize: 2100,
        lvl: 2,
    },
    {
        id: 10044,
        name: "CHALECO DE MITHRIL",
        type: "3",
        img: "10044.png",
        prop: ["Armadura +60"],
        effect: ["", ""],
        prize: 1400,
        lvl: 2,
    },
    {
        id: 10076,
        name: "ARMADURA DE LA VENGANZA",
        type: "3",
        img: "10076.png",
        prop: ["Fuerza +9", "Agilidad +9", "Daño +15"],
        effect: [
            "Pasiva única - Venganza: Refleja un 30% de daño físico y un 15% de daño mágico. El daño reflejado se trata como daño real.",
        ],
        prize: 2300,
        lvl: 2,
    },
    {
        id: 10077,
        name: "CRISTAL DE ALMA",
        type: "3",
        img: "10077.png",
        prop: [
            "Salud +450",
            "Maná +400",
            "Regeneración de salud +3",
            "Regeneración de maná +50",
        ],
        effect: [
            "Pasiva única - Lanzamiento rápido Ⅱ: Reduce el enfriamiento de las habilidades un 10%.",
        ],
        prize: 3300,
        lvl: 3,
    },
    {
        id: 10097,
        name: "CRISTAL DE FUERZA",
        type: "3",
        img: "10097.png",
        prop: ["Salud +600", "Armadura +35"],
        effect: [
            "Pasiva única: Resistencia a hechizos +15",
            "Habilidad activa - Guardián de cristal: Aumenta la Resistencia a hechizos en 20 durante 15 s para todos los aliados en un radio de 700.",
        ],
        prize: 5425,
        lvl: 5,
    },
    {
        id: 10257,
        name: "FUERZA DE ACERO",
        type: "3",
        img: "10257.png",
        prop: ["Armadura +90"],
        effect: [
            "Pasiva única: Esquivar +30%",
            "Pasiva única - Aura lenta: Al ser atacado, reduce la Velocidad de movimiento del atacante en 50 y la Velocidad de ataque en 30 durante 1,5 s.",
        ],
        prize: 4250,
        lvl: 4,
    },
    {
        id: 10263,
        name: "CORAZÓN DEL TITÁN",
        type: "3",
        img: "10263.png",
        prop: ["Salud +300", "Fuerza +35"],
        effect: [
            "Pasiva única - Renacimiento: Restaura un 2,5% de la Vida máxima por segundo. Si un héroe enemigo recibe daño, esta habilidad se desactiva durante 3 s para los héroes cuerpo a cuerpo o 5 s para los héroes a distancia.",
        ],
        prize: 5500,
        lvl: 5,
    },
    {
        id: 12309,
        name: "MAZA DEL JUICIO",
        type: "3",
        img: "12309.png",
        prop: ["Todos los atributos +10", "Armadura +70", "Maná +300"],
        effect: [
            "Pasiva única - Lanzamiento rápido Ⅲ: Reduce el enfriamiento de las habilidades un 15%",
            "Pasiva única - Maldición celestial: Invoca Trueno aplastante tras lanzar la habilidad, tu siguiente ataque inflige un 125% de Daño base como daño adicional, a la vez que ralentiza la Velocidad de movimiento del objetivo y de los enemigos cercanos un 30% durante 2 s en un radio de 300. Enfriamiento: 3s",
        ],
        prize: 5000,
        lvl: 5,
    },
    {
        id: 10030,
        name: "HACHA BARBARA",
        type: "3",
        img: "10030.png",
        prop: ["Fuerza +10"],
        effect: [""],
        prize: 1000,
        lvl: 1,
    },
    {
        id: 10048,
        name: "EMPERADOR RADIANTE",
        type: "3",
        img: "10048.png",
        prop: [
            "Salud +400",
            "Todos los Atributos +10",
            "Armadura +30",
            "Regeneración de salud +8",
        ],
        effect: [
            "Pasiva única, Llamarada II: Achicharra a los enemigos cercanos, infligiendo 50 + 1% de Vida máxima del objetivo de daño mágico por segundo en un radio de 200. (Inflige un 50% de daño a tropas y criaturas de la jungla).",
        ],
        prize: 5800,
        lvl: 5,
    },
    {
        id: 10069,
        name: "CORAZA DEL EMPERADOR",
        type: "3",
        img: "10069.png",
        prop: ["Armadura +90", "Velocidad de ataque +35"],
        effect: [
            "Pasiva única - Halo guardián: aumenta 30 puntos el blindaje de las unidades y edificios aliados cercanos en un radio de 1000",
            "Pasiva única - Pulso destructivo: Reduce 30 de armadura de las unidades y edificios enemigos cercanos en un radio de 1000",
            "Pasiva única - Danza del anillo: Otorga 15 de Velocidad de ataque a las unidades aliadas cercanas en un radio de 1000.",
        ],
        prize: 5250,
        lvl: 5,
    },
    {
        id: 10124,
        name: "GUARDIÁN DE HIELO",
        type: "3",
        img: "10124.png",
        prop: ["Salud +300", "Maná +250", "Poder de hechizo +30", "Armadura +60"],
        effect: [
            "Habilidad activa: Se activa para emitir una onda helada que inflige Inteligencia 3x de daño mágico a los enemigos en un radio de 600, a la vez que ralentiza su velocidad de movimiento un 40% durante 3s.",
            "Enfriamiento: 30s, Coste de maná: 50",
            "Pasiva única - Romper hechizo I:Reduce 8 veces la Resistencia a hechizos de todas las unidades enemigas en un radio de 1200.",
        ],
        prize: 4500,
        lvl: 4,
    },
    {
        id: 12316,
        name: "DEIDAD VENGATIVA",
        type: "3",
        img: "12316.png",
        prop: ["Fuerza +19", "Agilidad +19", "Inteligencia +10", "Daño +25"],
        effect: [
            "Pasiva única - Revancha: Refleja un 30% de daño físico y un 15% de daño mágico, todo tratado como daño puro",
            "Habilidad activa-Deidad vengativa: Invoca a una deidad vengativa en ti para aumentar el reflejo de daño al 80% durante 3 segundos. Enfriamiento: 30 s, Coste de maná: 40",
        ],
        prize: 4900,
        lvl: 4,
    },
    {
        id: 10265,
        name: "ESCUDO PÚRPURA",
        type: "3",
        img: "10265.png",
        prop: ["Salud +550", "Maná +250"],
        effect: [
            "Pasiva única: Resistencia a hechizos +20",
            "Pasiva única: Muro de hierro: Otorga un 70% de probabilidad de bloquear 80 de daño de cada ataque entrante para héroes cuerpo a cuerpo, o 40 para héroes a distancia.",
            "Pasiva única - Exorcismo II: Si tu Vida es inferior al 35% por recibir daño mágico, el daño mágico adicional se reduce un 35% durante 4s. Enfriamiento: 60s",
        ],
        prize: 4325,
        lvl: 4,
    },
    {
        id: 10085,
        name: "CORAZÓN DE GÁRGOLA",
        type: "3",
        img: "10085.png",
        prop: ["Todos los atributos +3", "Regeneración de salud +6/s'", "Regeneración de maná +100%"],
        effect: [
            "Pasiva única - Lanzamiento rápido Ⅲ：Reduce el Enfriamiento de habilidades un 15%",
            "Habilidad activa - Danza del anillo: Aumenta un 40% la Velocidad de movimiento y un 15 la Velocidad de ataque de todos los aliados en un radio de 1000 durante 4s. Coste de maná: 100. Enfriamiento: 30s",
        ],
        prize: 3000,
        lvl: 3,
    },
    {
        id: 10016,
        name: "BOTAS RAUDAS",
        type: "4",
        img: "10016.png",
        prop: ["", ""],
        effect: ["Atributo - Dash: Velocidad de movimiento: +50"],
        prize: 500,
        lvl: 1,
    },
    {
        id: 125020,
        name: "BOTAS GUARDIANAS",
        type: "4",
        img: "125020.png",
        prop: ["Armadura +35"],
        effect: [
            "Pasiva única: Velocidad de movimiento +80", "Probabilidad del 70% de bloquear 30/15 p. de daño para heroes cuerpo a cuerpo/a distancia.",
        ],
        prize: 1800,
        lvl: 2,
    },
    {
        id: 125030,
        name: "BOTAS INSPIRADORAS",
        type: "4",
        img: "125030.png",
        prop: ["+20 Poder mágico , regeneración de maná +25%"],
        effect: [
            "Pasiva única Reduce el tiempo de reutilizacion de la habilidad en 10%, limitado en 40%",
            "Pasiva única Velocidad de movimiento +80",
        ],
        prize: 1700,
        lvl: 2,
    },
    {
        id: 10100,
        name: "BOTAS DE GUERRA",
        type: "4",
        img: "10100.png",
        prop: ["Daño +10", "Velocidad de ataque +25"],
        effect: ["Pasiva única - Dash II: Velocidad de movimiento +80"],
        prize: 1450,
        lvl: 2,
    },
    {
        id: 12307,
        name: "BOTAS VITALES",
        type: "4",
        img: "12307.png",
        prop: ["Salud +300"],
        effect: ["Pasiva única - Dash II: Velocidad de movimiento: +80"],
        prize: 1600,
        lvl: 2,
    },
    {
        id: 10089,
        name: "BOTAS ARCANAS",
        type: "4",
        img: "10089.png",
        prop: ["Maná +250"],
        effect: [
            "Pasiva única - Dash II: Velocidad de movimiento: +80",
            "Habilidad Activa - Arcana I: Se activa para restaurar 270 de Maná a todos los aliados en un radio de 1000. Enfriamiento: 30s",
        ],
        prize: 1500,
        lvl: 2,
    },
    {
        id: 10302,
        name: "BOTAS SUPERSÓNICAS",
        type: "4",
        img: "10302.png",
        prop: ["", ""],
        effect: [
            "Pasiva única - Dash III: Velocidad de movimiento +90",
            "Concede un aura que aumenta un 6% la Velocidad de movimiento adicional a todos los aliados en un radio de 1000.",
        ],
        prize: 1600,
        lvl: 2,
    },
    {
        id: 125141,
        name: "GREBAS SAGRADAS",
        type: "4",
        img: "125141.png",
        prop: ["Maná +250", "Todos los atributos: +6", "Armadura: +25"],
        effect: [
            "Pasiva única - Dash II: Velocidad de movimiento: +80",
            "Pasiva única - Luz divina: Aumenta 4 veces la Regeneración de Vida de todos los aliados en un radio de 1000",
            "Habilidad activa - Curación II: Se activa para recuperar 300 de Vida y 300 de Maná de todos los aliados en un radio de 900, mientras otorga 12 de Armadura adicional durante 15s. Coste de maná: 100, Enfriamiento: 30s",
        ],
        prize: 4500,
        lvl: 4,

    },
    {
        id: 125161,
        name: "OJO EXORCISTA",
        type: "3",
        img: "125161.png",
        prop: ["Salud +550", "Maná +250"],
        effect: [
            "Pasiva única: Resistencia a hechizos +35",
            "Los heroes cuerpo a cuerpo se vuelven inmunes a los efectos de aturdimiento durante 3.5s y los heroes a distancia durante 2.5s y su duño magico tomado se reduce en 35%",
        ],
        prize: 4850,
        lvl: 4,
    },
    {
        id: 10300,
        name: "PODER DE GEA",
        type: "3",
        img: "10300.png",
        prop: ["Armadura +50"],
        effect: [
            "Pasiva única: Resistencia a hechizos +20",
            "Pasiva única: Esquivar +25%",
            "Actívala para aumentar la Vida máxima en 800 para los héroes cuerpo a cuerpo y en 400 para los héroes a distancia. Dura 10 s. Enfriamiento: 30s. Coste de maná: 50 s.",
        ],
        prize: 4300,
        lvl: 4,

    },
    {
        id: 125131,
        name: "PULSO RÁPIDO",
        type: "2",
        img: "125131.png",
        prop: [
            "Salud +350",
            "Maná +300",
            "Poder de Hechizo +70",
            "Regeneración de maná +100",
        ],
        effect: [
            "Pasiva única: Robo de vida mágica +15%",
            "Pasiva única - Lanzamiento rápido Ⅳ: Reduce el Enfriamiento de habilidades un 20%.",
        ],
        prize: 6450,
        lvl: 5,

    },
    {
        id: 12519,
        name: "GEMA DE DETECCIÓN",
        type: "5",
        img: "12519.png",
        prop: ["Todos los atributos +10"],
        effect: [
            "Pasiva única - Observar II: Cada vez que una unidad enemiga en un radio de 1000 muere y no recibe tu último golpe, ganas 10 monedas, recuperas 10 puntos de Vida y 5 de Maná.",
        ],
        prize: 2000,
        lvl: 2,
    },
    {
        id: 12520,
        name: "GEMA DE VISIÓN VERDADERA",
        type: "5",
        img: "12520.png",
        prop: ["Todos los atributos +20"],
        effect: [
            "Atributo - ObservadorIII Recibes un guardia observador cada 50s, almacenando hasta 3 guardias observadores",
            "Atributo de botínIII: Cuando una unidad enemiga muere, no asesinada por ti, en un radio de 1000 a tu alrededor, obtienes 15 de oro adicional y restauras 20 de salud y 10 de maná",
            "Pasiva Lanzamiento Único Rápido II: Reduce el tiempo de reutilización de habilidades en un 10%, acumulándose hasta un 40%. Activar Unica-Visión",
            "Pasiva única - Lanzamiento rápido Ⅱ: Detecta  Unidades enemigas invisibles dentro de un radio de 1200 a tu alrededor. tiempo de reutilizacion: 40s.",
        ],
        prize: 4000,
        lvl: 4,
    },
    {
        id: 125101,
        name: "ESPADA DEL FENIX",
        type: "1",
        img: "125101.png",
        prop: ["Daño +30"],
        effect: ["Pasiva única: Probabilidad de crítico. +15%"],
        prize: 2150,
        lvl: 2,
    },
    {
        id: 125111,
        name: "ESPIRAL DEL CICLON",
        type: "1",
        img: "125111.png",
        prop: ["Daño +25", "Velocidad de ataque +15"],
        effect: [
            "Pasiva única - Golpe de precisión I: el 40% de tus ataques no fallarán.",
        ],
        prize: 2000,
        lvl: 2,

    },
    // {
    //     id: "k13",
    //     name: "ALABARDA DE PLATA",
    //     type: "1",
    //     img: "k13.jpg",
    //     prop: ["Damage +25"],
    //     effect: [
    //         "Attribute: Pure Damage Transfers 12% of damage of your attacks and physical abilities into Pure Damage.",
    //     ],
    //     prize: 1800,
    //     lvl: 2,
    // },
    // {
    //     id: "k14",
    //     name: "HOJA SOMBRIA",
    //     type: "1",
    //     img: "k14.jpg",
    //     prop: ["Damage +30"],
    //     effect: [
    //         "Unique Passive - Thorn Slash I: Your attacks reduce target's 30 points of Armor for 5s, and cannot be stacked.",
    //     ],
    //     prize: 2550,
    //     lvl: 3,
    // },
    {
        id: 125151,
        name: "GERBAS DEL BAILARÍN",
        type: "4",
        img: "125151.png",
        prop: ["Todos los atributos +3", "Regeneración de salud +6/s", "Regeneración de maná +100%"],
        effect: [
            "Pasiva única - Dash III: Velocidad de movimiento +90",
            "Pasiva única - Lanzamiento rápido Ⅲ: Reduce el enfriamiento de las habilidades un 15%",
            "Pasiva única - Paso sagrado: Aumenta la Velocidad de Movimiento en un 8% para todos los aliados dentro de un rango de 1000",
            "Habilidad Activa - Danza del Anillo: Aumenta un 30% la Velocidad de movimiento y un 15 la Velocidad de ataque a todos los aliados en un radio de 1000 durante 4s. Coste de maná: 100.",
        ],
        prize: 4800,
        lvl: 4,
    },
    {
        id: 12533,
        name: "RUINA DE ZAKAR",
        type: "2",
        img: "12533.png",
        prop: ["Poder de Hechizo +60", "Velocidad de Ataque +35"],
        effect: [
            "Pasiva única - Lanzamiento rápido III: Reduce el enfriamiento de las habilidades un 15% (hasta un 40%)",
            "Atributo - Desplazamiento I: Velocidad de movimiento +10%",
            "Pasiva única - Tizón: Cada ataque básico inflige al golpe 20 + 15% Poder de hechizo de daño mágico.",
        ],
        prize: 4500,
        lvl: 4,
    },
    {
        id: 12532,
        name: "ROMPEDOMOS",
        type: "2",
        img: "12532.png",
        prop: ["Inteligencia +20", "Poder de hechizo +110", "Regeneración de maná +100%"],
        effect: [
            "Activa - Rompe la cúpula: Inflige 600 de daño mágico a la unidad enemiga objetivo, cada 1 Poder de Hechizo otorga 1 bonus de daño mágico. Coste de maná: 250. Enfriamiento: 35s. Alcance: 850",
        ],
        prize: 6000,
        lvl: 5,
    },
    {
        id: 12317,
        name: "CORONETA RESPLANDECIENTE",
        type: "2",
        img: "12317.png",
        prop: ["Salud +350", "Maná +250", "Poder de hechizo +70"],
        effect: [
            "Pasiva única: reducción de enfriamiento 10%",
            "Pasiva única: Corre hacia adelante por 800, evitando terrenos.",
        ],
        prize: 6350,
        lvl: 5,
    },
    // {
    //     id: 12502,
    //     name: "GUARDIAN BOOTS",
    //     type: "4",
    //     img: "12502.jpg",
    //     prop: ["Armor +35"],
    //     effect: [
    //         "Attribute - Dash II: Movement Speed: +80",
    //         "Unique Passive -Iron Wall: Gives 70% chance to block 30/15 damage for melee/ranged.",
    //     ],
    //     prize: 1800,
    //     lvl: 2,
    // },
    // {
    //     id: 12503,
    //     name: "WIZARD BOOTS",
    //     type: "4",
    //     img: "12503.jpg",
    //     prop: ["Spell Power +20"],
    //     effect: [
    //         "Unique Passive - Fast Casting Ⅱ: Reduces abilities cooldown by 10%",
    //         "Unique Passive - Dash II: Movement Speed: +80",
    //     ],
    //     prize: 1800,
    //     lvl: 2,
    // },
    {
        id: 12684,
        name: "COLLAR DE DESPERTAR",
        type: "3",
        img: "12684.png",
        prop: ["Todos los atributos +25", "Salud +150"],
        effect: [
            "Pasiva única: Activa las fuerzas latentes mas poderosas de un heroe, otorgandole una posicion ventajosa. ",
        ],
        prize: 5000,
        lvl: 5,

    },
    {
        id: 12321,
        name: "GEMA DE DETECCION ",
        type: "5",
        img: "12321.png",
        prop: ["Todos los atributos +10"],
        effect: [
            "Reduce el tiempo de reutilizacion de tus guardianes observadoras en 15s. cuando una unidad enemiga muere, no asesinada por ti, dentro de un radio de 1000 a tu alrededor, obtienes 10 de oro adicional y restauras 10 de salud y 5 de mana",
        ],
        prize: 2000,
        lvl: 2,
    },
    // {
    //     id: 12321,
    //     name: "GEMA DE DETECCION ",
    //     type: "5",
    //     img: "12519.png",
    //     prop: ["All Attributes +10"],
    //     effect: [
    //         "Reduce el tiempo de reutilizacion de tus guardianes observadoras en 15s. cuando una unidad enemiga muere, no asesinada por ti, dentro de un radio de 1000 a tu alrededor, obtienes 10 de oro adicional y restauras 10 de salud y 5 de mana",
    //     ],
    //     prize: 2000,
    //     lvl: 2,
    // },
];

export default ItemData2;
